<?php
	
	if(isset($this->layout()->datossector))
		$datossector=$this->layout()->datossector;

	
?>
<script type="text/javascript">
       
	   var emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$";
 
	   $(document).ready(function() {
            
			
			
			 $("#sector").on('change', function () {
					$("#sector option:selected").each(function () {
						elegido=$(this).val();
						$.post("/Usuario/utilidades",{tipo:'1',sector:elegido,nivel:'0'}, function(data){
							$("#combonivel").html(data);
						});			
					});
		   });
		
			
			
			
			
			$("#btn_guardar").click(function(){


				if($("#login").val().length<5)
				{
					alert("Debe Ingresar Correctamente Login de Usuario");
					$("#login").focus();
					return false;
				} 
				
				if(!$("#nivel").val())
				{
					alert("Debe Seleccionar el Nivel de Permisos");
					$("#nivel").focus();
					return false;
				}
				
				if(!$("#sector").val())
				{
					alert("Debe Seleccionar el Departamento");
					$("#sector").focus();
					return false;
				}
				
				if($("#nombreapellido").val().length<5)
				{
					alert("Debe Ingresar Correctamente Nombre y Apellido Usuario");
					$("#nombreapellido").focus();
					return false;
				} 
				
			
				if($("#email").val().length<5 || !$("#email").val().match(emailPattern))
				{
					alert("Debe Ingresar Correctamente un E-mail");
					$("#email").focus();
					return false;		
				} 
				
				if($("#clave").val().length<5)
				{
					alert("Debe Ingresar Correctamente Password de Usuario");
					$("#clave").focus();
					return false;
				} 
				

				if (!confirm("Desea Guardar los Datos del Usuario?")) 
				{
				
					return false;
				
				} else {
				
						grabar();
									
				}
				



            });
        }); 


		function grabar()
  		{

			var parametros = {
									"login" : $("#login").val(),
									"nivel" : $("#nivel").val(),
									"sector" : $("#sector").val(),
									"nombreapellido" : $("#nombreapellido").val(),
									"email" : $("#email").val(),
									"clave" : $("#clave").val(),
									"privado" : $("#privado").val(),
									"notiasig" : $("#notiasig").val(),
									"accion" : 'grabar'
							};
			
			
			$.ajax({
							data:  parametros,
							url:   '/Usuario/agregarusuarioprocess', 
							type:  'post', 
							beforeSend: function () {
														$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>Procesando solicitud..</div></div>");
													},
	
							success:  function (response) { 
							
										var str=response;
										var res = str.split("|");
								
										if(res[0]=='OK')
										{
												$("#divNotificaciones").html("<div class='panel panel-success'><div class='panel-heading'>Datos almacenados correctamente</div></div>");
	
												$('#volver_bot').focus();
												//limpia formulario
												$('#oForm').trigger("reset");
										
										}else{
											
												$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>"+res[1]+"</div></div>");
											
										}
									
							}
					});
	  
  		} 	





</script>


 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
					
						   <div id="divNotificaciones">
						   </div>	
					
							<div class="panel panel-default">
				
									<div class="panel-heading">
                                        <button type="button" class="btn btn btn-default">INGRESO USUARIO</button>
										<a href="/Usuario"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
							        </div>
                                    <div class="panel-body">
                
										   
				
				                            <form role="form" id="oForm" name="oForm">
                                                    <div class="form-group">
                                                        <label>Login Usuario (*)</label>
														<input id="login" name="login" class="form-control" maxlength="10" type="text" title="Aqu&iacute; debe ingresar el login de usuario con el cual ingresar&aacute; al sistema, m&iacute;nimo 5 caracteres">
                                                        <p class="help-block">M&iacute;nimo 5 carateres sin espacio</p>
                                     				</div>
                                                  
												    <div class="form-group">
                                                        <label>Departamento (*)</label>
                                                        <select class="form-control" id="sector" name="sector">
															<option value="">[SELECCIONE]</option>
															<?php
															if(isset($datossector))
															{
																foreach($datossector as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS01_SECTORID"]?>"><?php echo $valor["SIS01_SECTORDESCRIPCION"]?></option>
																<?
																}
															}		
															?>
														</select>
													</div>
                                                
												
												 	<div id="combonivel">
													</div>
                                                
												
												  
												    <div class="form-group">
                                                        <label>Nombre / Apellido (*)</label>
                                                        <input class="form-control" type="text" id="nombreapellido" maxlength="50"  name="nombreapellido">
                                                    </div>
                                                    
													  <div class="form-group">
                                                        <label>E-mail (*)</label>
                                                        <input class="form-control" type="text" id="email" maxlength="100"  name="email">
                                                    
													
													</div>
                                                    				
													<div class="form-group">
                                                        <label>Password (*)</label>
                                                        <input class="form-control" type="text" maxlength="10" id="clave" name="clave" title="Aqu&iacute; debe ingresar la password de usuario con el cual ingresar&aacute; al sistema, m&iacute;nimo 5 caracteres">
                                                        <p class="help-block">M&iacute;nimo 5 carateres</p>
                                                    </div>
                                                    						
													
													
													<div class="form-group">
															<label>Es Usuario Privado (*)</label>
															
															<select class="form-control" id="privado" name="privado">
																<option value="1">SI</option>
																<option value="0">NO</option>
															</select>
															
														
											        </div>
          											<div class="form-group">
															<label>Notificar (*)</label>
															<select class="form-control" id="notiasig" name="notiasig">
																<option value="1">SI</option>
																<option value="0">NO</option>
															</select>
												    </div>
          											
													<button type="button" class="btn btn-info" id="btn_guardar">Guardar</button>
										    </form>
                                    </div>

							</div>
				
					 </div>
				 </div>

 </div>