<div class="col-md-12">
   <div class="panel panel-info">
															
				 <div class="row">
					 <div class="col-lg-12 col-md-12 col-sm-12">
					   <div class="table-responsive">
				
				
										<table class="table table-hover">
											<thead>
												<tr>
													<th colspan="5">Usuarios del Sistema</th>
												</tr>
												<tr>
													<th>ID</th>
													<th>NOMBRE</th>
													<th>E-MAIL</th>
													<th>NIVEL</th>
													<th>OPCIONES</th>
												</tr>
											</thead>
											<tbody>
												
												<tr>
													<td>aaedo</td>
													<td>Alejandra Aedo</td>
													<td>aaedo@compumat.cl</td>
													<td>Desarrollo</td>
													<td>
													
													  <button class="btn btn-primary"><i class="glyphicon glyphicon-search"></i>Editar</button>
                               					      <button class="btn btn-danger"><i class="glyphicon glyphicon-home"></i>Eliminar</button>
                               
													
													</td>
												</tr>
											</tbody>
									   </table>
							
						   
						   </div>
				
					 </div>
				 </div>


							

		 </div>
	 </div>
						
