<?php
	
	if(isset($this->layout()->datosusuarios))
		$datosusuarios=$this->layout()->datosusuarios;
	
	if(isset($this->layout()->total_usuarios))
		$total_usuarios=$this->layout()->total_usuarios;
	
	if(isset($this->layout()->pagina))
		$pagina=$this->layout()->pagina;

	if(isset($this->layout()->num_paginas))
		$num_paginas=$this->layout()->num_paginas;

	if(isset($this->layout()->usuario_ini))
		$usuario_ini=$this->layout()->usuario_ini;

	if(isset($this->layout()->usuario_fin))
		$usuario_fin=$this->layout()->usuario_fin;
		
	
?>
<div class="col-md-12">
		   
		   <div id="divNotificacionesCentral">
		   </div>									 
							
		   
		   <div class="panel panel-info">
																	
						 <div class="row">
							 <div class="col-lg-12 col-md-12 col-sm-12">
						
								
										   <div class="table-responsive">
									
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<tr>
																		<th colspan="5">Usuarios del Sistema (<?php echo $total_usuarios?>)</th>
																	</tr>
																	<tr>
																		<th colspan="5">
																		<a href="/Usuario/agregarusuario/"><button class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Agregar</button></a>
																		</th>
																	</tr>
																	<tr>
																		<th></th>
																		<th>ID</th>
																		<th>NOMBRE</th>
																		<th>E-MAIL</th>
																		<th>NIVEL</th>
																	</tr>
																</thead>
																<tbody>
																<?php
																		if(isset($datosusuarios))
																		{
																			foreach($datosusuarios as $clave => $valor)
																			{
																			?>
																				<tr>
																					<td>
																				
																						<div class="btn-group">
																							<button data-toggle="dropdown" class="btn btn-success dropdown-toggle">Opci&oacute;n <span class="caret"></span></button>
																							<ul class="dropdown-menu">
																								<li><a href="#" onclick="carga_editar('<?php echo $valor["ED01_USUARIOID"]?>')">Editar</a></li>
																								<li><a href="#" onclick="accion_eliminar('<?php echo $valor["ED01_USUARIOID"]?>')">Eliminar</a></li>
																								<li><a href="#" data-toggle="modal" data-target="#myModal_<?php echo $valor["ED01_USUARIOID"]?>">Detalle</a></li>
																							</ul>
																						</div>
																				
																				
																					<div class="modal fade" id="myModal_<?php echo $valor["ED01_USUARIOID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																								<div class="modal-dialog">
																											<div class="modal-content">
																								
																														<div class="modal-header">
																															<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
																															<h4 class="modal-title" id="myModalLabel">Usuario : <?php echo $valor["ED01_USUARIOID"]?></h4>
																														</div>
																														<div class="modal-body">
																															<strong>USUARIOID : </strong><?php echo $valor["ED01_USUARIOID"]?><br><br>
																															<strong>NIVEL : </strong><?php echo $valor["SIS02_NIVELID"]?><br><br>
																															<strong>SECTOR : </strong><?php echo $valor["SIS01_SECTORID"]?><br><br>
																															<strong>NOMBRE : </strong><?php echo $valor["ED01_NOMBREAPELLIDO"]?><br><br>
																															<strong>EMAIL : </strong><?php echo $valor["ED01_EMAIL"]?><br><br>
																															<strong>ES PRIVADO : </strong><?php echo $valor["ED01_ESPRIVADO"]?><br><br>
																															<strong>AVISAR ASIGNACION : </strong><?php echo $valor["ED01_AVISARASIGNACION"]?><br><br>
																															<strong>AVISAR SOLICITUD : </strong><?php echo $valor["ED01_AVISARSOLICITUD"]?><br><br>
																															<strong>FECHA INGRESO : </strong><?php echo $valor["FECHA_INGRESO"]?><br><br>
																															<strong>FECHA ULTIMA ACTUALIZACION : </strong><?php echo $valor["FECHA_ACTUALIZACION"]?><br><br>
																														</div>
																														<div class="modal-footer">
																															<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
																														</div>
																										
																								
																											</div>
																								</div>
																						</div>

																					
																					
																					
																				
																				
																				
																				
																					</td>
																					<td><?php echo $valor["ED01_USUARIOID"]?></td>
																					<td><?php echo $valor["ED01_NOMBREAPELLIDO"]?></td>
																					<td><a href="mailto:<?php echo $valor["ED01_EMAIL"]?>"><?php echo $valor["ED01_EMAIL"]?></a></td>
																					<td><?php echo $valor["SIS02_NIVELID"]?></td>
																				</tr>
																			<?
																			}
																		}		
																?>
																</tbody>
														   </table>
												
															<ul class="pagination">
															  <?php
															  for($i=1;$i<=$num_paginas;$i++)
															  {
															  ?>	
															  <li <?php if(intval($pagina)==intval($i)){?>class="active"<?php }?>><a href="#" onclick="carga_pagina('<?php echo $i;?>')"><?php echo $i;?> <?php if(intval($pagina)==intval($i)){?><span class="sr-only">(current)</span><?php }?></a></li>
															  <?
															  }
															  ?>	
															</ul>
											   
											   </div>

								
							 </div>
						 </div>
		
				 </div>
	 </div>