<?php
	
	$ASISTENCIAID=$this->layout()->ASISTENCIAID;
?>
	<script type="text/javascript">
		
		   var match= ["application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","image/jpeg","image/png","image/jpg","image/gif","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel","application/pdf"];
			
		
		   $(document).ready(function() {
		
		
		
				$("#archivo").change(function() {
			
					var file = this.files[0];
					var imagefile = file.type;
					
					if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2]) || (imagefile==match[3]) || (imagefile==match[4]) || (imagefile==match[5]) || (imagefile==match[6]) || (imagefile==match[7]) || (imagefile==match[8]) || (imagefile==match[9]) || (imagefile==match[10]) || (imagefile==match[11]))){
						alert('Por favor seleccione un archivo del tipo (JPEG / JPG / PNG / GIF / TXT / DOC / XLS / PDF / PPT).');
						$("#archivo").val('');
						return false;
					}
			
				});
		
		
		
				$("#calendario").datepicker({dateFormat: 'dd/mm/yy'});
	 

				$("#btn_guardar").click(function(){
	
	
					
					if($("#calendario").val().length<10)
					{
						alert("Debe Ingresar la Fecha del Seguimiento");
						$("#calendario").focus();
						return false;
					} 
					
			
					if($("#detalle").val().length<5)
					{
						alert("Debe Ingresar el Detalle del Seguimiento");
						$("#detalle").focus();
						return false;
					} 
		

					if (!confirm("Desea Guardar el Seguimiento a la Asistencia?")) 
					{
					
						return false;
					
					} else {
					
							grabar();
										
					}
					
	
				});
			}); 
	
	
	
			function grabar()
			{
	
				var file_data = $('#archivo').prop('files')[0];   
				var form_data = new FormData();                  
				form_data.append('file', file_data);

				form_data.append('asistenciaid',$("#asistenciaid").val());
				form_data.append('calendario', $("#calendario").val());
				form_data.append('detalle', $("#detalle").val());
				form_data.append('resuelto', $("#resuelto").val());
				form_data.append('archivo', $("#archivo").val());
				form_data.append('accion', 'grabar');
				
				
				$.ajax({
								url:   '/Bitacoraasistencia/agregarbitacoraasistenciaprocess', 
								dataType: 'text',  
								cache: false,
								contentType: false,
								processData: false,
								data: form_data,                         
								type: 'post',
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>Procesando solicitud..</div></div>");

														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
													
													$("#divNotificaciones").html("<div class='panel panel-success'><div class='panel-heading'>Datos almacenados correctamente</div></div>");
													$('#volver_bot').focus();
													//limpia formulario
													$('#oForm').trigger("reset");
											
											}else{
												
													$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>"+res[1]+"</div></div>");

												
											}
										
								}
						});
		  
			} 	
	
	
	
	
	
	</script>


 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
						   </div>	
				
						
							<div class="panel panel-default">
				
									<div class="panel-heading">
                                        <button type="button" class="btn btn btn-default">INGRESO SEGUIMIENTO ASISTENCIA</button>
										<a href="/Asistencia"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
							        </div>
                
				
				                    <div class="panel-body">
					 
															<form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
																 
																	   <input type="hidden" id="asistenciaid" name="asistenciaid" value="<?php echo $ASISTENCIAID?>">
												 
																 
																	   <div class="form-group">
																			<label>Fecha Seguimiento (*)</label>
																			<input type="text" class="form-control" id="calendario" readonly="readonly">
																	   </div>
																	  
																		<div class="form-group">
																			<label>Detalle Seguimiento (*)</label>
																			<textarea class="form-control" rows="5" id="detalle" name="detalle"></textarea>
																		</div>
															  
															  			 
																		 <div class="form-group" style="background-color:#EEEEEE">
																			<label class="control-label col-lg-4">Adjunto</label>
																			<div class="">
																				 <input type="file" name="archivo" id="archivo" class="btn btn-info">
																			</div>
																		</div>
																		 
														
																		<div class="form-group">
																			<label>Est&aacute; Resuelto? (*)</label>
																			<select class="form-control" id="resuelto" name="resuelto">
																			  <option value="NO">NO</option>
																			  <option value="SI">SI</option>
																			 </select>
																		<div>
															
																					
																	  <button type="button" class="btn btn-info" id="btn_guardar">Guardar</button>
				
				
				
															</form>
        			                         
										</div>
				
								</div>
				
					 </div>
				 
				 
				 </div>

 </div>