<?php
	
		if(isset($this->layout()->datoscolegio))
			$datoscolegio=$this->layout()->datoscolegio;
	
		if(isset($this->layout()->datosproducto))
			$datosproducto=$this->layout()->datosproducto;
		
		if(isset($this->layout()->datosclasificador))
			$datosclasificador=$this->layout()->datosclasificador;
	
		if(isset($this->layout()->datosmodulos))
			$datosmodulos=$this->layout()->datosmodulos;
			
		
		if(isset($this->layout()->datossector))
			$datossector=$this->layout()->datossector;

		
	
		$INCIDENTEID=$this->layout()->INCIDENTEID;
		$LABORATORIOID=$this->layout()->LABORATORIOID;
		$LABORATORIODESCRIPCION=$this->layout()->LABORATORIODESCRIPCION;
		$PRODUCTOID=$this->layout()->PRODUCTOID;
		$FECHATICKET=$this->layout()->FECHATICKET;
		$NOMBRESOLICITANTE=$this->layout()->NOMBRESOLICITANTE;
		$TELEFONOSOLICITANTE=$this->layout()->TELEFONOSOLICITANTE;
		$EMAILSOLICITANTE=$this->layout()->EMAILSOLICITANTE;
		$PRIORIDAD=$this->layout()->PRIORIDAD;
		$DETALLETICKET=$this->layout()->DETALLETICKET;
		$GESTIONINMEDIATA=$this->layout()->GESTIONINMEDIATA;
		$TIPOCONTACTO=$this->layout()->TIPOCONTACTO;
		$NIVELSOPORTE=$this->layout()->NIVELSOPORTE;
		$CLASIFICADORID=$this->layout()->CLASIFICADORID;
		$CLASIFICADORDESCRIPCION=$this->layout()->CLASIFICADORDESCRIPCION;
		$ARCHIVOADJUNTO=$this->layout()->ARCHIVOADJUNTO;
		$NOMBREARCHIVOADJUNTO=$this->layout()->NOMBREARCHIVOADJUNTO;
		$TIPOARCHIVOADJUNTO=$this->layout()->TIPOARCHIVOADJUNTO;
		$NUMALUMNOSAFECTADOS=$this->layout()->NUMALUMNOSAFECTADOS;
		$NIVELDELPROGRAMA=$this->layout()->NIVELDELPROGRAMA;
		$CODIGOMODULO=$this->layout()->CODIGOMODULO;
		$NUMEJERCICIO=$this->layout()->NUMEJERCICIO;
		$ESTADO=$this->layout()->ESTADO;
		$USUARIOSELECCIONADO=$this->layout()->USUARIOSELECCIONADO;
		$SECTOR=$this->layout()->SECTOR;
	
	
?>

<script type="text/javascript">
		
	    
				$.post("/Incidente/utilidades",{tipo:'1',nivel:'<?php echo $NIVELSOPORTE;?>',clasificador:'<?php echo $CLASIFICADORID;?>'}, function(data){
							$("#comboclasificador").html(data);
				});			
				
				$.post("/Usuario/usuarioxsector",{sector:'<?php echo $SECTOR;?>',derivado:'<?php echo $USUARIOSELECCIONADO;?>',filtronivel:'1,4,5'}, function(data){
							$("#comboderivados").html(data);
				});			
			
		
		
			   var emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$";
			   var match= ["application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","image/jpeg","image/png","image/jpg","image/gif","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel","application/pdf"];
			   var val = $("#colegio").val("<?php echo $LABORATORIOID?> | <?php echo $LABORATORIODESCRIPCION?>");
			   var val2 = $("#modulo").val("<?php echo $CODIGOMODULO?>");
			
		
				$("#num_pregunta").on('input', function () { 
					this.value = this.value.replace(/[^0-9]/g,'');
				});
				
				$("#num_alumnos").on('input', function () { 
					this.value = this.value.replace(/[^0-9]/g,'');
				});
						
		
				 $("#nivelsoporte").on('change', function () {
					$("#nivelsoporte option:selected").each(function () {
						elegido=$(this).val();
						$.post("/Incidente/utilidades",{tipo:'1',nivel:elegido,clasificador:'0'}, function(data){
							$("#comboclasificador").html(data);
						});			
					});
			   });
		
		
			  $("#sector").on('change', function () {
					$("#sector option:selected").each(function () {
						elegido=$(this).val();
						$.post("/Usuario/usuarioxsector",{sector:elegido,derivado:'0',filtronivel:'1,4,5'}, function(data){
							$("#comboderivados").html(data);
						});			
					});
			   });
		
		
		
		
				$("#archivo").change(function() {
			
					var file = this.files[0];
					var imagefile = file.type;
					
					if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2]) || (imagefile==match[3]) || (imagefile==match[4]) || (imagefile==match[5]) || (imagefile==match[6]) || (imagefile==match[7]) || (imagefile==match[8]) || (imagefile==match[9]) || (imagefile==match[10]) || (imagefile==match[11]))){
						alert('Por favor seleccione un archivo del tipo (JPEG / JPG / PNG / GIF / TXT / DOC / XLS / PDF / PPT).');
						$("#archivo").val('');
						return false;
					}
			
				});
		
		
		
				$("#calendario").datepicker({dateFormat: 'dd/mm/yy'});
	 
				
				function valida_grabar()
				{
		
								
							val = $("#colegio").val();
							var obj = $("#colegio_lista").find("option[value='" + val + "']");
							
							if(obj != null && obj.length > 0)
							{
								//OK  
							}else{
									alert("Debe Ingresar Correctamente el Colegio Asociado");
									$("#colegio").focus();
									return false;
								 }	
								
							
							if(!$("#producto").val())
							{
								alert("Debe Seleccionar el Producto");
								$("#producto").focus();
								return false;
							}
							
											
							if($("#calendario").val().length<10)
							{
								alert("Debe Ingresar la Fecha de Solicitud");
								$("#calendario").focus();
								return false;
							} 
							
							if($("#nombreapellido").val().length<5)
							{
								alert("Debe Ingresar Correctamente Nombre y Apellido del Contacto");
								$("#nombreapellido").focus();
								return false;
							} 
								
							if($("#email").val().length>0 && !$("#email").val().match(emailPattern))
							{
								alert("Debe Ingresar Correctamente un E-mail");
								$("#email").focus();
								return false;		
							} 
							
						
							if(!$("#prioridad").val())
							{
								alert("Debe Seleccionar Prioridad");
								$("#prioridad").focus();
								return false;
							}			
			
							if($("#detalle").val().length<5)
							{
								alert("Debe Ingresar el Detalle del Incidente");
								$("#detalle").focus();
								return false;
							} 
				
							if(!$("#tipocontacto").val())
							{
								alert("Debe Seleccionar Tipo Contacto");
								$("#tipocontacto").focus();
								return false;
							}			
		
							if(!$("#nivelsoporte").val())
							{
								alert("Debe Seleccionar Nivel Soporte");
								$("#nivelsoporte").focus();
								return false;
							}			
			
					if(!$("#sector").val())
					{
						alert("Debe Seleccionar Departamento");
						$("#sector").focus();
						return false;
					}			
							if(!$("#clasificadores").val())
							{
								alert("Debe Seleccionar Clasificador");
								$("#clasificadores").focus();
								return false;
							}			
					
					if(!$("#derivado").val())
					{
						alert("Debe Seleccionar Derivado/Resuelto X:");
						$("#derivado").focus();
						return false;
					}			
							if (!confirm("Desea Guardar el Incidente?")) 
									{
							
								return false;
							
							} else {
							
									grabar();
												
							}
							
		
			
			}
	
	
	
	
			function grabar()
			{
	
				
				var file_data = $('#archivo').prop('files')[0];   
				var form_data = new FormData();                  
				form_data.append('file', file_data);
				
				form_data.append('incidenteid',$("#incidenteid").val());
				form_data.append('colegio',$("#colegio").val());
				form_data.append('producto', $("#producto").val());
				form_data.append('calendario', $("#calendario").val());
				form_data.append('nombreapellido', $("#nombreapellido").val());
				form_data.append('telefono', $("#telefono").val());
				form_data.append('email', $("#email").val());
				form_data.append('prioridad', $("#prioridad").val());
				form_data.append('detalle', $("#detalle").val());
				form_data.append('gestioninmediata', $("#gestioninmediata").val());
				form_data.append('tipocontacto', $("#tipocontacto").val());
				form_data.append('nivelsoporte', $("#nivelsoporte").val());
				form_data.append('clasificadores', $("#clasificadores").val());
				form_data.append('modulo', $("#modulo").val());
				form_data.append('num_pregunta', $("#num_pregunta").val());
				form_data.append('num_alumnos', $("#num_alumnos").val());
				form_data.append('nivel', $("#nivel").val());
				form_data.append('archivo', $("#archivo").val());
				form_data.append('sector', $("#sector").val());
				form_data.append('derivado', $("#derivado").val());
				form_data.append('estado', $("#estado").val());
				form_data.append('accion', 'grabar');
				
				
				$.ajax({
								url:   '/Incidente/editarincidenteprocess', 
								dataType: 'text',  
								cache: false,
								contentType: false,
								processData: false,
								data: form_data,                         
								type: 'post',
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>Procesando solicitud..</div></div>");

														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
												$("#formulario").html("<div class='panel panel-success'><div class='panel-heading' id='volver_frame'>Datos almacenados correctamente<br><br><a href='/Incidente/index/busqueda/"+res[1]+"'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a></div></div>");
												$('#volver_bot').focus();
									
											}else{
												
													$("#formulario").html("<div class='panel panel-primary'><div class='panel-heading' id='volver_frame'>"+res[1]+"<br><br><a href='/Incidente'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a></div></div>");
													$('#volver_bot').focus();
										
											}
										
								}
						});
		  
			} 	
	
	

</script>
				
	
 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
						   </div>	
				
						  <div class="panel panel-info">
								
									<div class="panel-heading">
                                    	<button type="button" class="btn btn btn-default">EDITAR INCIDENTE</button>
										<a href="/Incidente"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
									</div>
                                   
					
					
					
					                <div class="panel-body">
				
											 
										
				                            <form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
												 
												    <input type="hidden" id="incidenteid" name="incidenteid" value="<?php echo $INCIDENTEID?>">
																
																
																<div class="row">
															
																			<div class="col-md-12">
																				<div class="form-group">
																					<label>Colegio (*)</label>
							
																					<input list="colegio_lista" class="form-control" id="colegio">
																					<datalist id="colegio_lista">
																						<?php
																						if(isset($datoscolegio))
																						{
																							foreach($datoscolegio as $clave => $valor)
																							{
																							?>
																								<option value="<?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?>" <?php if($LABORATORIOID==$valor["SIS03_LABORATORIOID"]) echo "selected='selected'"?>>
																							<?
																							}
																						}		
																						?>
																					</datalist>
																				</div>
																			</div>
																	  
																</div>		
							
																<div class="row">
																	<div class="col-md-4 col-sm-4">
																				   <div class="form-group">
																						<label>Producto (*)</label>
																						<select class="form-control" id="producto" name="producto">
																							<?php
																							if(isset($datosproducto))
																							{
																								foreach($datosproducto as $clave => $valor)
																								{
																								?>
																									<option value="<?php echo $valor["SIS04_PRODUCTOID"]?>" <?php if($PRODUCTOID==$valor["SIS04_PRODUCTOID"]) echo "selected"?>><?php echo $valor["SIS04_PRODUCTODESCRIPCION"]?></option>
																								<?
																								}
																							}		
																							?>
																						</select>
																					</div>
                                                  
																	</div>												 
																	<div class="col-md-4 col-sm-4">
                														   <div class="form-group">
																				<label>Fecha Incidente (*)</label>
																				<input type="text" class="form-control" id="calendario" readonly="readonly" value="<?php echo $FECHATICKET?>">
																		   </div>
																	</div>  
															  </div>		  
													
													
															<div class="row">
																<div class="col-md-4 col-sm-4">
                													
																	   <div class="form-group">
																			<label>Nombre Solicitante (*)</label>
																			<input class="form-control" type="text" id="nombreapellido" maxlength="100"  name="nombreapellido" value="<?php echo $NOMBRESOLICITANTE?>">
																	   </div>
												 
																</div>												 
																<div class="col-md-4 col-sm-4">
                		  										 
																	   <div class="form-group">
																			<label>Tel&eacute;fono Solicitante</label>
																			<input class="form-control" type="text" id="telefono" maxlength="50"  name="telefono" value="<?php echo $TELEFONOSOLICITANTE?>">
																	   </div>

																</div>  
															</div>		  
																		  
															
															<div class="row">
														
																<div class="col-md-12">
															
																	   <div class="form-group">
																			<label>E-mail Solicitante</label>
																			<input class="form-control" type="text" id="email" maxlength="100"  name="email" value="<?php echo $EMAILSOLICITANTE?>">
																	   </div>
														  
																</div>  
															</div>		
														
															<div class="row">
																<div class="col-md-4 col-sm-4">
                													
																		<div class="form-group">
																			<label>Prioridad (*)</label>
																			<select class="form-control" id="prioridad" name="prioridad">
																				<option value="1" <?php if($PRIORIDAD=="1") echo "selected"?>>ALTA</option>
																				<option value="0" <?php if($PRIORIDAD=="0") echo "selected"?>>BAJA</option>
																			</select>
																		</div>
										
																</div>												 
																<div class="col-md-4 col-sm-4">
                		  											
																		<div class="form-group">
																			<label>Tipo Contacto (*)</label>
																			<select class="form-control" id="tipocontacto" name="tipocontacto">
																				<option value="CHAT" <?php if($TIPOCONTACTO=="CHAT") echo "selected"?>>CHAT</option>
																				<option value="TELEFONO" <?php if($TIPOCONTACTO=="TELEFONO") echo "selected"?>>TELEFONO</option>
																				<option value="EMAIL" <?php if($TIPOCONTACTO=="EMAIL") echo "selected"?>>EMAIL</option>
																				<option value="INTERNO"  <?php if($TIPOCONTACTO=="INTERNO") echo "selected"?>>INTERNO</option>
																			</select>
																		</div>

																</div>  
												
												
																<div class="col-md-4 col-sm-4">

																		<div class="form-group">
																			<label>Nivel (*)</label>
																			<select class="form-control" id="nivel" name="nivel">
																				<option value="1 BASICO" <?php if($NIVELDELPROGRAMA=="1 BASICO") echo "selected"?>>1 BASICO</option>
																				<option value="2 BASICO" <?php if($NIVELDELPROGRAMA=="2 BASICO") echo "selected"?>>2 BASICO</option>
																				<option value="3 BASICO" <?php if($NIVELDELPROGRAMA=="3 BASICO") echo "selected"?>>3 BASICO</option>
																				<option value="4 BASICO" <?php if($NIVELDELPROGRAMA=="4 BASICO") echo "selected"?>>4 BASICO</option>
																				<option value="5 BASICO" <?php if($NIVELDELPROGRAMA=="5 BASICO") echo "selected"?>>5 BASICO</option>
																				<option value="6 BASICO" <?php if($NIVELDELPROGRAMA=="6 BASICO") echo "selected"?>>6 BASICO</option>
																				<option value="7 BASICO" <?php if($NIVELDELPROGRAMA=="7 BASICO") echo "selected"?>>7 BASICO</option>
																				<option value="8 BASICO" <?php if($NIVELDELPROGRAMA=="8 BASICO") echo "selected"?>>8 BASICO</option>
																				<option value="I MEDIO" <?php if($NIVELDELPROGRAMA=="I MEDIO") echo "selected"?>>I MEDIO</option>
																				<option value="II MEDIO" <?php if($NIVELDELPROGRAMA=="II MEDIO") echo "selected"?>>II MEDIO</option>
																				<option value="III MEDIO" <?php if($NIVELDELPROGRAMA=="III MEDIO") echo "selected"?>>III MEDIO</option>
																				<option value="IV MEDIO" <?php if($NIVELDELPROGRAMA=="IV MEDIO") echo "selected"?>>IV MEDIO</option>

																			</select>
																		</div>

																</div>  
					
												
												
															</div>		  
																		
																		
																		
															<div class="row">
														
																	<div class="col-md-12">
																				
																			<div class="form-group">
																				<label>Detalle Incidente (*)</label>
																				<textarea class="form-control" rows="3" id="detalle" name="detalle"><?php echo $DETALLETICKET?></textarea>
																			</div>
																	</div>  
						
															</div>			   
																								
												
															<div class="row">
														
																	<div class="col-md-12">
																				
																			<div class="form-group">
																				<label>Gesti&oacute;n Inmediata</label>
																				<textarea class="form-control" rows="2" id="gestioninmediata" name="gestioninmediata"><?php echo $GESTIONINMEDIATA?></textarea>
																			</div>
																	</div>  
						
															</div>		
												
										
														<div class="row">
														
																<div class="col-md-4 col-sm-4">
						
																		<div class="form-group">
																				<label>M&oacute;dulo</label>
																				<input list="modulo_lista" class="form-control" id="modulo">
																				<datalist id="modulo_lista">
																					<?php
																					if(isset($datosmodulos))
																					{
																						foreach($datosmodulos as $clave => $valor)
																						{
																						?>
																							<option value="<?php echo $valor["SIS05_CODIGOMODULO"]?>">
																						<?
																						}
																					}		
																					?>
																				</datalist>
																		</div>
	
																</div>												 
														
																<div class="col-md-4 col-sm-4">
													
																	<div class="form-group">
																		<label>N&uacute;mero Pregunta</label>
																		<input class="form-control" type="text" id="num_pregunta" maxlength="3"  name="num_pregunta" value="<?php echo $NUMEJERCICIO?>">
																	</div>
	
																</div>  
					
					
																<div class="col-md-4 col-sm-4">
																	
																		<div class="form-group">
																			<label>Num-Afectados</label>
																			<input class="form-control" type="text" id="num_alumnos" maxlength="3"  name="num_alumnos" value="<?php echo $NUMALUMNOSAFECTADOS?>">
																		</div>

																</div>												 
														
					
														</div>			   


														
														
																	

														<div class="row">
																<div class="col-md-12">
			
																	 <div class="form-group" style="background-color:#EEEEEE">
																		<label class="control-label col-lg-4">Adjunto </label>
																		 <input type="file" name="archivo" id="archivo" class="btn btn-info">
																		 <?php
																		 if(trim($NOMBREARCHIVOADJUNTO)!="")
																		 {
																		 ?>
																		 <strong> [ Archivo actual : <a href="<?php echo $ARCHIVOADJUNTO?>" target="_blank"><?php echo $NOMBREARCHIVOADJUNTO?></a> ] </strong>
																		 <?php
																		 }
																		 ?>
																	</div>
														 

																</div>  
					
														</div>			   

														 

														<div class="row">
															  <div class="col-md-4 col-sm-4">

																	<div class="form-group">
																		<label>Nivel Soporte (*)</label>
																		<select class="form-control" id="nivelsoporte" name="nivelsoporte">
																			<option value="">[SELECCIONE]</option>
																			<option value="1" <?php if($NIVELSOPORTE=="1") echo "selected"?>>Soporte 1er Nivel Mesa de Ayuda</option>
																			<option value="2" <?php if($NIVELSOPORTE=="2") echo "selected"?>>Soporte 2do Nivel</option>
																		</select>
																	</div>

																</div>												 
																<div class="col-md-4 col-sm-4">
													
																	 <div class="form-group">
																
																			 <label>Departamento (*)</label>
																				<select class="form-control" id="sector" name="sector">
																				<option value="">[SELECCIONE]</option>
																				<?php
																				if(isset($datossector))
																				{
																					foreach($datossector as $clave => $valor)
																					{
																					?>
																						<option value="<?php echo $valor["SIS01_SECTORID"]?>" <?php if(trim($SECTOR)==$valor["SIS01_SECTORID"] && trim($SECTOR)!="") echo "selected"?>><?php echo $valor["SIS01_SECTORDESCRIPCION"]?></option>
																					<?
																					}
																				}		
																				?>
																			</select>
	
																	</div>	
																</div>		  
															</div>		
															<div class="row">
																<div class="col-md-12">
																	<div id="comboclasificador">
																	</div>
																</div>  
															</div>		
			
															<div class="row">
																<div class="col-md-4 col-sm-4">
					
														 				<div id="comboderivados">
																		
																			<div class="form-group">
																				<label>Derivado a : (*)</label>
																				<select class="form-control" id="derivado" name="derivado">
																					<option value="">[SELECCIONE]</option>
																				</select>
																			</div>
																		
																		</div>
					
																</div>									
																<div class="col-md-4 col-sm-4">
																	 <div class="form-group">
																		<label>Estado (*)</label>
																		<select class="form-control" id="estado" name="estado">
																			<?php if($ESTADO!="GESTIONADO"){?>
																			<option value="PENDIENTE" <?php if($ESTADO=="PENDIENTE") echo "selected"?>>PENDIENTE</option>
																			<?php }?>
																			<option value="DERIVADO" <?php if($ESTADO=="DERIVADO" || $ESTADO=="GESTIONADO") echo "selected"?>>DERIVADO</option>
																			<option value="RESUELTO" <?php if($ESTADO=="RESUELTO") echo "selected"?>>RESUELTO</option>
																			<option value="MEJORA-FUTURA" <?php if($ESTADO=="MEJORA-FUTURA") echo "selected"?>>MEJORA-FUTURA</option>
																		</select>
																	</div>
																</div>  
															</div>		
					
					
															<div class="row">
																<div class="col-md-12">
																	  <button type="button" class="btn btn-info" id="btn_guardar" onclick="valida_grabar()">Guardar</button>
																</div>  
															</div>		
				
										    </form>
                                  
								      </div>
								  
								  </div>

							</div>
				
				 
				 </div>

 </div>