<?php

	if(isset($this->layout()->acceso_funcionalidades))
		$acceso_funcionalidades=$this->layout()->acceso_funcionalidades;
	
	if(isset($this->layout()->datos_seguimiento))
		$datos_seguimiento=$this->layout()->datos_seguimiento;
		
	if(isset($this->layout()->datossolicitudes))
		$datossolicitudes=$this->layout()->datossolicitudes;
	
	if(isset($this->layout()->total_filas))
		$total_filas=$this->layout()->total_filas;
	
	if(isset($this->layout()->pagina))
		$pagina=$this->layout()->pagina;

	if(isset($this->layout()->num_paginas))
		$num_paginas=$this->layout()->num_paginas;

	if(isset($this->layout()->registro_ini))
		$registro_ini=$this->layout()->registro_ini;

	if(isset($this->layout()->registro_fin))
		$registro_fin=$this->layout()->registro_fin;
	
	if(isset($this->layout()->busqueda))
		$busqueda=$this->layout()->busqueda;
		
	if(isset($this->layout()->datos_derivados))
		$datos_derivados=$this->layout()->datos_derivados;
		
	
	if($total_filas < $registro_fin)
	   $ULTIMO_REG=$total_filas;
	else   
	   $ULTIMO_REG=$registro_fin;
	
	
?>
<script type="text/javascript">
 
	   
	   $("#realizar_busqueda_incidentes").click( function()
       {
         	if($("#busqueda").val()!="")
			{
				carga_pagina_incidente('1',$("#busqueda").val());
		  	}
		 }
        );
	   
   
	   
</script>
	   
<div class="col-md-12">
		   
		   <div id="divNotificacionesCentral">
		   </div>									 
						
						
						
		<div class="panel-footer">
			<div class="input-group">
				<input type="text" name="busqueda" id="busqueda" class="form-control" value="<?php echo $busqueda?>" placeholder="" data-toggle="tooltip" title="Puedes buscar por : RBD / NUM INCIDENTE / ESTADO (PEN - DER - RES)" />
				<span class="input-group-btn">
					<button class="btn btn-success" type="button" id="realizar_busqueda_incidentes">BUSCAR</button>
				</span>
			</div>
		 </div>
	
							
		   
		   <div class="panel panel-info">
																	
						 <div class="row">
							 <div class="col-lg-12 col-md-12 col-sm-12">
						
								
											 
								
								
										   <div class="table-responsive">
									
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<tr>
																		<th colspan="5">Incidentes del Sistema (<?php echo $total_filas?>), visualizando desde el <?php echo $registro_ini?> al <?php echo $ULTIMO_REG?></th>
																	</tr>
																	<tr>
																		<th colspan="5">
																		<?php
																		if(isset($acceso_funcionalidades[2]) && trim($acceso_funcionalidades[2])=="1")
																		{																								
																		?>	
																		<a href="/Incidente/agregarincidente/"><button class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Agregar</button></a>
																		<?php
																		}
																		?>	
																		</th>
																	</tr>
																	<tr>
																		<th></th>
																		<th>NUM.</th>
																		<th>COLEGIO</th>
																		<th>FECHA INCIDENTE</th>
																		<th>ESTADO</th>
																	</tr>
																</thead>
																<tbody>
																<?php
																		if(isset($datossolicitudes))
																		{
																			foreach($datossolicitudes as $clave => $valor)
																			{
																			?>
																				<tr>
																					<td>
																						
																					
																					   <div class="btn-group">
																							<button data-toggle="dropdown" class="btn btn-success dropdown-toggle">Opci&oacute;n <span class="caret"></span></button>
																							<ul class="dropdown-menu">
																								<?php
																								if(isset($acceso_funcionalidades[1]) && trim($acceso_funcionalidades[1])=="1")
																								{																								
																								?>
																								<li><a href="#" data-toggle="modal" data-target="#myModal_<?php echo $valor["ED03_TICKETID"]?>">Detalle</a></li>
																								<?php
																								}
																							
																								if($valor["ED03_ESTADO"]=="PENDIENTE")
																								{ 
																											if(isset($acceso_funcionalidades[3]) && trim($acceso_funcionalidades[3])=="1")
																											{																								
																											?>	
																											<li><a href="#" onclick="carga_editar('<?php echo $valor["ED03_TICKETID"]?>')">Editar</a></li>
																											<?php
																											}
																											if(isset($acceso_funcionalidades[4]) && trim($acceso_funcionalidades[4])=="1")
																											{																								
																											?>	
																											<li><a href="#" onclick="accion_eliminar('<?php echo $valor["ED03_TICKETID"]?>')">Eliminar</a></li>
																											<?php
																											}
																								}
																								?>
																											<li class="divider"></li>
																											<?php
																											
																											
																											//4 estados
																											//Pendiente : no se ha hecho nada
																											//Derivado : cuando se generó incidente
																											//Resuelto : cuando está todo ok
																											//Asistencia : cuando se generó asistencia
																											
																											
																											if($valor["ED03_ESTADO"]=="DERIVADO")
																											{ 
																													if(isset($acceso_funcionalidades[5]) && trim($acceso_funcionalidades[5])=="1")
																													{																								
																													?>	
																													<li><a href="/Bitacora/agregarbitacora/incidenteid/<?php echo $valor["ED03_TICKETID"]?>">Seguimiento</a></li>
																													<?php
																													}
																											}
																											
																											
																											if(isset($acceso_funcionalidades[6]) && trim($acceso_funcionalidades[6])=="1")
																											{																								
																												if($valor["ED03_ESTADO"]!="ASISTENCIA")
																												{ 
																												?>
																													<li><a href="#" onclick="accion_generar('<?php echo $valor["ED03_TICKETID"]?>')">Generar Asistencia</a></li>
																												<?php
																												}
																											}
																											?>
																							
																							</ul>
																						</div>
																						
																						
																						
																						<div class="modal fade" id="myModal_<?php echo $valor["ED03_TICKETID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																								<div class="modal-dialog">
																											<div class="modal-content">
																								
																														<div class="modal-header">
																															<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
																															<h4 class="modal-title" id="myModalLabel">Incidente n&uacute;mero : <?php echo $valor["ED03_TICKETID"]?></h4>
																														</div>
																														<div class="modal-body">
																					

																															 <div class="panel panel-default">
																																<div class="panel-heading">
																																	DETALLE INCIDENTE
																																</div>
																																<div class="panel-body">
																																	<ul class="nav nav-tabs">
																																		<li class="active"><a href="#home<?php echo $valor["ED03_TICKETID"]?>" data-toggle="tab">INFO</a>
																																		</li>
																																	
																																		<?php
																																		if(isset($datos_seguimiento))
																																		{
																																			foreach($datos_seguimiento as $clave_seg => $valor_seg)
																																			{
																																				if($valor_seg["ED03_TICKETID"]==$valor["ED03_TICKETID"])
																																				{
																																			?>
																																			<li class=""><a href="#profile<?php echo $valor_seg["ED04_SEGTICKETID"]?>" data-toggle="tab">SEG. <?php echo $valor_seg["ED04_SEGFECHA"]?></a></li>
																																			<?php
																																				}
																																			}
																																		}
																																		?>
																																	
																																	</ul>
																										
																																	<div class="tab-content">
																																		
																																		<div class="tab-pane fade active in" id="home<?php echo $valor["ED03_TICKETID"]?>">
																																				<br>
																																				<p>
																																				<strong>RBD : </strong><?php echo $valor["SIS03_LABORATORIOID"]?><br><br>
																																				<strong>COLEGIO : </strong><?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?><br><br>
																																				<strong>NUM INCIDENTE : </strong><?php echo $valor["ED03_TICKETID"]?><br><br>
																																				<strong>PRODUCTO : </strong><?php echo $valor["SIS04_PRODUCTOID"]?><br><br>
																																				<strong>FECHA TICKET : </strong><?php echo $valor["FECHATICKET"]?><br><br>
																																				<strong>TELEFONO SOLICITANTE : </strong><?php echo $valor["ED03_TELEFONOSOLICITANTE"]?><br><br>
																																				<strong>EMAIL SOLICITANTE : </strong><?php echo $valor["ED03_EMAILSOLICITANTE"]?><br><br>
																																				<strong>PRIORIDAD : </strong><?php echo $valor["ED03_PRIORIDAD"]?><br><br>
																																				<strong>TIPO CONTACTO : </strong><?php echo $valor["ED03_TIPOCONTACTO"]?><br><br>
																																				<strong>NIVEL : </strong><?php echo $valor["ED03_NIVELSOPORTE"]?><br><br>
																																				<strong>CLASIFICADOR : </strong><?php echo $valor["SIS07_CLASIFICADORDESCRIPCION"]?><br><br>
																																				<strong>NUM ALUMNOS AFECTADOS : </strong><?php echo $valor["ED03_NUMALUMNOSAFECTADOS"]?><br><br>
																																				<strong>NIVEL: </strong><?php echo $valor["ED03_NIVELDELPROGRAMA"]?><br><br>
																																				<strong>MODULO : </strong><?php echo $valor["SIS05_CODIGOMODULO"]?><br><br>
																																				<strong>NUM EJERCICIO : </strong><?php echo $valor["ED03_NUMEJERCICIO"]?><br><br>
																																																									
																																				<strong>DETALLE : </strong><br><?php echo nl2br($valor["ED03_DETALLETICKET"])?><br><br>
																																				<?php
																																				if(trim($valor["ED03_ARCHIVOADJUNTO"])!="")
																																				{	
																																				?>
																																				<strong>ARCHIVO ADJUNTO : </strong><br>
																																				
																																				<strong><a href="<?php echo $valor["ED03_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor["ED03_NOMBREARCHIVOADJUNTO"]?></a></strong>
																																				
																																				<br><br>
																																				
																																				<?php
																																				}
																																				?>
																																				<strong>SOLICITANTE : </strong><?php echo $valor["ED03_NOMBRESOLICITANTE"]?><br><br>
																																				<strong>ULTIMA ACTUALIZACI&Oacute;N : </strong><?php echo $valor["FECHAULTIMAACTUALIZACION"]?><br><br>
																																				<strong>ESTADO : </strong><?php echo $valor["ED03_ESTADO"]?><br><br>
																																	
																																				<?php 
																																				$IDTICKET=$valor["ED03_TICKETID"];
																																	
																																				if(isset($datos_derivados["$IDTICKET"]["ED01_USUARIOID"]))
																																				{
																																				?>
																																				<strong>DERIVADO A : </strong><?php echo $datos_derivados["$IDTICKET"]["ED01_USUARIOID"]?><br><br>
																																				<?php
																																				}
																																				?>
																																				</p>
																																
																																		</div>
																																	
																																
																																	  <?php
																																		if(isset($datos_seguimiento))
																																		{
																																			foreach($datos_seguimiento as $clave_seg => $valor_seg)
																																			{
																																				if($valor_seg["ED03_TICKETID"]==$valor["ED03_TICKETID"])
																																				{
																																			?>
																																			<div class="tab-pane fade" id="profile<?php echo $valor_seg["ED04_SEGTICKETID"]?>">
																																				<br>
																																				<p>
																																				<strong>USUARIO : </strong><?php echo $valor_seg["ED01_USUARIOID"]?><br><br>
																																				<strong>FECHA : </strong><?php echo $valor_seg["ED04_SEGFECHA"]?><br><br>
																																				<strong>DETALLE : </strong><br><?php echo nl2br($valor_seg["ED04_SEGCOMENTARIOS"])?><br><br>
																																																									
																																				<?php
																																				if(trim($valor_seg["ED04_ARCHIVOADJUNTO"])!="")
																																				{	
																																				?>
																																				<strong>ARCHIVO ADJUNTO : </strong><br>
																																				
																																				<strong><a href="<?php echo $valor_seg["ED04_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor_seg["ED04_NOMBREARCHIVOADJUNTO"]?></a></strong>
																																				
																																				<br><br>
																																				
																																				<?php
																																				}
																																				?>
																																				<strong>COMENTARIO DEL SEGUIMIENTO : </strong><br><?php echo nl2br($valor_seg["ED04_REGISTRODETALLECAMBIO"])?><br><br>
																																				</p>
																																			</div>
																																		
																																		
																																			<?php
																																				}
																																			}
																																		}
																																		?>
																																	
																																	
																																	
																																	</div>
																																</div>
																															</div>
																																																											
																												


																															
																												
																														</div>
																														<div class="modal-footer">
																															<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
																														</div>
																										
																								
																											</div>
																								</div>
																						</div>

																					
																					
																					
																					
																					
																					</td>
																				
																					<td><?php echo $valor["ED03_TICKETID"]?></td>
																					<td><?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?></td>
																					<td><?php echo $valor["FECHATICKET"]?></td>
																					<td><?php echo $valor["ED03_ESTADO"]?></td>
																				</tr>
																			<?
																			}
																		}		
																?>
																</tbody>
														   </table>
												
															<ul class="pagination">
															  <?php
															  for($i=1;$i<=$num_paginas;$i++)
															  {
															  ?>	
															  <li <?php if(intval($pagina)==intval($i)){?>class="active"<?php }?>><a href="#" onclick="carga_pagina('<?php echo $i;?>','<?php echo $busqueda?>')"><?php echo $i;?> <?php if(intval($pagina)==intval($i)){?><span class="sr-only">(current)</span><?php }?></a></li>
															  <?
															  }
															  ?>	
															</ul>
											   
											   </div>

								
							 </div>
						 </div>
		
				 </div>
	 </div>
