<?

	if(isset($_COOKIE['cok_login']) && trim($_COOKIE['cok_login'])!="") 
	{
			$TEXTO_LOGIN=trim($_COOKIE['cok_login']);
			$DESACTIVAR_FOCUS_LOGIN=1;
	}else{	
			$DESACTIVAR_FOCUS_LOGIN=0;
	}
	
	if(isset($_COOKIE['cok_clave']) && trim($_COOKIE['cok_clave'])!="") 
	{
			$TEXTO_PASSWORD=trim($_COOKIE['cok_clave']);
			$DESACTIVAR_FOCUS_PASSWORD=1;
	}else{
			$DESACTIVAR_FOCUS_PASSWORD=0;
	
	}


	if(isset($_COOKIE['cok_recuerdame']) && trim($_COOKIE['cok_recuerdame'])!="") 
	{
			$DESACTIVAR_RECUERDAME=1;
	}else{
			$DESACTIVAR_RECUERDAME=0;
	
	}
	
	
	
	
	
?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-DESK / Ingreso</title>

    <!-- BOOTSTRAP STYLES-->
    <link href="assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="assets/css/font-awesome.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
	<!-- JQUERY SCRIPTS -->
	<script src="/assets/js/jquery-1.10.2.js"></script>

	<script type="text/javascript">
 
 
	   function accion_logearse()
	   {
	
	
				if($("#login").val().length<5)
				{
					alert("Debes Ingresar Correctamente Login de Usuario");
					$("#login").focus();
					return false;
				} 
				
				
				if($("#clave").val().length<5)
				{
					alert("Debe Ingresar Correctamente Password de Usuario");
					$("#clave").focus();
					return false;
				} 
	
	
				if (document.getElementById('recuerdame').checked==true) {
					CHECKEADO=1;
				} else {
					CHECKEADO=0;
				}
			
	
				var parametros = {
									"login" : $("#login").val(),
									"clave" : $("#clave").val(),
									"recuerdame" : CHECKEADO
								};
				
				$.ajax({
								data:  parametros,
								url:   '/Loginusuario/validarusuario', 
								type:  'post', 
								evalscripts : true,
								success:  function (response) { 
								
								
										var str=response;
										var res = str.split("|");
								
										if(res[0]=='OK')
										{
								
												var urlentrada = "/Fichacolegio";   
												$(location).attr('href',urlentrada);								
										
										}else{
												$("#divNotificacionesCentral").html("<div class='panel-body'><div class='alert alert-danger alert-dismissable'>"+res[1]+"</div></div>");
											}				
								}
						});
						
	

 	   }	
	
	
	
		$(document).keypress(function(event){
			var keycode = (event.keyCode ? event.keyCode : event.which);
			if(keycode == '13'){
				document.getElementById("envia_accion_logearse").click();
			}
		});
	
	
	</script>

</head>
<body style="background-color: #E2E2E2;">
    <div class="container">
        <div class="row text-center " style="padding-top:100px;">
            <div class="col-md-12">
                <img src="assets/img/logo_edesk.png" />
            </div>
        </div>
         <div class="row ">
               
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
                           
						
						   
                            <div class="panel-body">
                                <form role="form">
                                    <hr />
                                    
									   
									<div id="divNotificacionesCentral">
									</div>
									<h5>Ingresa tus datos de acceso</h5>
                                       <br />
                                       <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-tag"  ></i></span>
                                            <input type="text" class="form-control" <?php if($DESACTIVAR_FOCUS_LOGIN==0){?>placeholder="Tu Login" onFocus="$('#login').attr('placeholder','').placeholder()" <?php }else{?> value="<?php echo $TEXTO_LOGIN?>"<?php }?> id="login" name="login" maxlength="10" />
                                        </div>
                                       <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-lock"  ></i></span>
                                            <input type="password" class="form-control"  <?php if($DESACTIVAR_FOCUS_PASSWORD==0){?>placeholder="Tu Password" onFocus="$('#clave').attr('placeholder','').placeholder()" <?php }else{?> value="<?php echo $TEXTO_PASSWORD?>"<?php }?> id="clave" name="clave" maxlength="10" />
                                        </div>
                                        <div class="form-group">
                                            <label class="checkbox-inline">
                                                <input type="checkbox"  name="recuerdame" id="recuerdame" value="1" <?php if($DESACTIVAR_RECUERDAME==1){?>checked<?php } ?>/> Recu&eacute;rdame
                                            </label>
                                            <span class="pull-right">
                                                   <a href="/Login/recordarclave" >¿OLVIDASTE TU PASSWORD? </a> 
                                            </span>
                                        </div>
                                     	<a href="#" onClick="accion_logearse();" class="btn btn-primary " id="envia_accion_logearse">Aceptar</a>
									</form>
                            </div>
                           
                        </div>
                
                
        </div>
    </div>

</body>
</html>