<?php
	 //recupera paràmetros principales
	 $LABORATORIODESCRIPCION=$this->layout()->LABORATORIODESCRIPCION;
	 $LABORATORIOID=$this->layout()->LABORATORIOID;


?>
			<div class="row">
                    <div class="col-md-12">
                        <h1 class="page-head-line">Ficha Colegio</h1>
                        <h1 class="page-subhead-line">Visi&oacute;n resumida de las actividades de un colegio</h1>

                    </div>
            </div>
              
          
		  
		    <div class="row">
               
						<div class="col-md-4 col-sm-4">
							<div class="panel panel-primary">
								<div class="panel-heading">
									Colegio : <?php echo $LABORATORIOID?>, <?php echo $LABORATORIODESCRIPCION?>
								</div>
								<div class="panel-body">
									<p><strong>Cursos:</strong> I MEDIO-A</p>
									<p><strong>Asesor:</strong> Amèrica Yañez</p>
									<p><strong>Productos:</strong> Inicial, Bàsica, Media</p>
									<p><strong>Productos:</strong>ONLINE LOCAL</p>
							
							
								</div>
							</div>
						</div>
					
				
				
						<div class="col-md-6 col-sm-6 col-xs-12">
							<div class="panel panel-info">
								<div class="panel-heading">
								   CONSULTA ALUMNO
								</div>
								<div class="panel-body">
									<form role="form">
												<div class="form-group">
													<label>Ingrese Rut:</label>
													<input class="form-control" type="text" size="10">
												</div>
													<div class="form-group">
														<label>Producto : </label>
														<select class="form-control">
															<option>INICIAL</option>
															<option>BASICA</option>
															<option>MEDIA</option>
														</select>
											   </div>
										 
												<button type="submit" class="btn btn-info">Consultar</button>
		
											</form>
									</div>
								</div>
						  </div>
						  
			</div>
			
			<div class="row">
			 
				   <div class="col-md-6 col-sm-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								Tabs
							</div>
							<div class="panel-body">
								<ul class="nav nav-pills">
									<li class="active"><a href="#home-pills" data-toggle="tab">Ultimos Incidentes</a>
									</li>
									<li class=""><a href="#profile-pills" data-toggle="tab">Ultimas Solicitudes Internas</a>
									</li>
									<li class=""><a href="#messages-pills" data-toggle="tab">Ultimas Atenciones T&eacute;cnicas</a>
									</li>
								</ul>
	
								<div class="tab-content">
									<div class="tab-pane fade active in" id="home-pills">
								
											 <div class="panel panel-default">
								   
												<div class="panel-heading">
													Ultimos Incidentes
												</div>
												
												<div class="panel-body">
													<div class="table-responsive">
														<table class="table">
															<thead>
																<tr>
																	<th>#</th>
																	<th>First Name</th>
																	<th>Last Name</th>
																	<th>Username</th>
																</tr>
															</thead>
															<tbody>
																<tr class="success">
																	<td>1</td>
																	<td>Mark</td>
																	<td>Otto</td>
																	<td>@mdo</td>
																</tr>
																<tr class="info">
																	<td>2</td>
																	<td>Jacob</td>
																	<td>Thornton</td>
																	<td>@fat</td>
																</tr>
																<tr class="warning">
																	<td>3</td>
																	<td>Larry</td>
																	<td>the Bird</td>
																	<td>@twitter</td>
																</tr>
																<tr class="danger">
																	<td>4</td>
																	<td>John</td>
																	<td>Smith</td>
																	<td>@jsmith</td>
																</tr>
															</tbody>
														</table>
													</div>
												</div>
											</div>
								
								
								
								
									</div>
									<div class="tab-pane fade" id="profile-pills">
									
									
									     <div class="panel panel-success">
											<div class="panel-heading">
											  	Ultimas Solicitudes Internas
											</div>
											<div class="panel-body" style="padding: 0px;">
												<div class="chat-widget-main">
				
				
												
												
												
												
														<table class="table table-hover">
															<thead>
																<tr>
																	<th>#</th>
																	<th>First Name</th>
																	<th>Last Name</th>
																	<th>Username</th>
																</tr>
															</thead>
															<tbody>
																<tr>
																	<td>1</td>
																	<td>Mark</td>
																	<td>Otto</td>
																	<td>@mdo</td>
																</tr>
																<tr>
																	<td>2</td>
																	<td>Jacob</td>
																	<td>Thornton</td>
																	<td>@fat</td>
																</tr>
																<tr>
																	<td>3</td>
																	<td>Larry</td>
																	<td>the Bird</td>
																	<td>@twitter</td>
																</tr>
																<tr>
																	<td>4</td>
																	<td>Larry</td>
																	<td>the Bird</td>
																	<td>@twitter</td>
																</tr>
															</tbody>
														</table>
									
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												
												</div>
											</div>
										</div>

									
									
									</div>
									<div class="tab-pane fade" id="messages-pills">
									
									
											  <div class="panel panel-default">
												<div class="panel-heading">
													Ultimas Atenciones T&eacute;cnicas
												</div>
												<div class="panel-body">
													<div class="table-responsive">
														<table class="table table-hover">
															<thead>
																<tr>
																	<th>#</th>
																	<th>First Name</th>
																	<th>Last Name</th>
																	<th>Username</th>
																</tr>
															</thead>
															<tbody>
																<tr>
																	<td>1</td>
																	<td>Mark</td>
																	<td>Otto</td>
																	<td>@mdo</td>
																</tr>
																<tr>
																	<td>2</td>
																	<td>Jacob</td>
																	<td>Thornton</td>
																	<td>@fat</td>
																</tr>
																<tr>
																	<td>3</td>
																	<td>Larry</td>
																	<td>the Bird</td>
																	<td>@twitter</td>
																</tr>
																<tr>
																	<td>4</td>
																	<td>Larry</td>
																	<td>the Bird</td>
																	<td>@twitter</td>
																</tr>
															</tbody>
														</table>
													</div>
												</div>
											</div>
									
									
									
									</div>
								</div>
							</div>
						</div>
					</div>

			</div>