<?php
	 //recupera paràmetros principales
	 $LABORATORIOID=$this->layout()->LABORATORIOID;
	 $LABORATORIODESCRIPCION=$this->layout()->LABORATORIODESCRIPCION;
	 $SIS03_ESTADO=$this->layout()->SIS03_ESTADO;
	 $SIS03_CURSOS=$this->layout()->SIS03_CURSOS;
	 $SIS03_ASESOR=$this->layout()->SIS03_ASESOR;
	 $SIS03_PRODUCTOS=$this->layout()->SIS03_PRODUCTOS;
	 $SIS03_CONEMATLOCAL=$this->layout()->SIS03_CONEMATLOCAL;
	
	if(isset($this->layout()->datosticket))
		$datosticket=$this->layout()->datosticket;

	if(isset($this->layout()->datossolicitud))
		$datossolicitud=$this->layout()->datossolicitud;
	
	if(isset($this->layout()->datosasistencias))
	   $datosasistencias=$this->layout()->datosasistencias;
	
	
?>
   
			<div class="col-md-4 col-sm-4">
			
				<div class="panel panel-primary">
					<div class="panel-heading">
						<strong>Colegio : </strong><?php echo $LABORATORIOID?> <?php echo $LABORATORIODESCRIPCION?>
					</div>
					<div class="panel-body">
						<p><strong>Cursos : </strong><?php echo $SIS03_CURSOS?></p>
						<p><strong>Asesor : </strong><?php echo $SIS03_ASESOR?></p>
						<p><strong>Productos : </strong><?php echo $SIS03_PRODUCTOS?></p>
						<p><strong>&iquest;Tiene Emat-Local? : </strong> <?=($SIS03_CONEMATLOCAL=="1")?'SI':'NO'?></p>
					</div>
				</div>
			
			</div>
			<div class="col-md-6 col-sm-6 col-xs-12">
		
		
					
						<div class="panel panel-info">
							<div class="panel-heading">
								Bit&aacute;cora Colegio
							</div>
							<div class="panel-body">
								<ul class="nav nav-pills">
									<!--class="active"-->
									<li class=""><a href="#profile-pills" data-toggle="tab">Solicitudes Internas</a>
									</li>
									<li class=""><a href="#home-pills" data-toggle="tab">Incidentes</a>
									</li>
									<li class=""><a href="#messages-pills" data-toggle="tab">Atenciones T&eacute;cnicas</a>
									</li>
								</ul>
	
								<div class="tab-content">

											 <!-- active in -->
									<div class="tab-pane fade" id="home-pills">


									 <div class="panel panel-success">
											<div class="panel-heading">
													Ultimos 10 Incidentes
											</div>
											<div class="panel-body" style="padding: 0px;">
												<div class="chat-widget-main">
				
														<table class="table table-hover">
															<thead>
																<tr>
																	<th>#</th>
																	<th>Fecha</th>
																	<th>Solicitante</th>
																	<th>Nivel</th>
																	<th>Detalle</th>
																</tr>
															</thead>
															<tbody>
																<?php
																if(isset($datosticket))
																{
																	foreach($datosticket as $clave => $valor)
																	{
																	?>
																	<tr>
																		<td><?php echo $valor["ED03_TICKETID"]?></td>
																		<td><?php echo $valor["ED03_FECHATICKET"]?></td>
																		<td><?php echo $valor["ED03_NOMBRESOLICITANTE"]?></td>
																		<td><?php echo $valor["ED03_NIVELSOPORTE"]?></td>
																		<td><a href="#" data-toggle="modal" data-target="#myModal_tic_<?php echo $valor["ED03_TICKETID"]?>">Detalle</a></td>
																		<td>
																			<div class="modal fade" id="myModal_tic_<?php echo $valor["ED03_TICKETID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																				<div class="modal-dialog">
																					<div class="modal-content">
																							<div class="modal-header">
																									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
																									<h4 class="modal-title" id="myModalLabel"><strong>INCIDENTE NUMERO : <?php echo $valor["ED03_TICKETID"]?></strong></h4>
																								</div>
																								<div class="modal-body">
																									
																										<strong>RBD : </strong><?php echo $valor["SIS03_LABORATORIOID"]?><br><br>
																										<strong>COLEGIO : </strong><?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?><br><br>
																										<strong>NUM INCIDENTE : </strong><?php echo $valor["ED03_TICKETID"]?><br><br>
																										<strong>PRODUCTO : </strong><?php echo $valor["SIS04_PRODUCTOID"]?><br><br>
																										<strong>FECHA TICKET : </strong><?php echo $valor["ED03_FECHATICKET"]?><br><br>
																										<strong>TELEFONO SOLICITANTE : </strong><?php echo $valor["ED03_TELEFONOSOLICITANTE"]?><br><br>
																										<strong>EMAIL SOLICITANTE : </strong><?php echo $valor["ED03_EMAILSOLICITANTE"]?><br><br>
																										<strong>PRIORIDAD : </strong><?php echo $valor["ED03_PRIORIDAD"]?><br><br>
																										<strong>TIPO CONTACTO : </strong><?php echo $valor["ED03_TIPOCONTACTO"]?><br><br>
																										<strong>NIVEL : </strong><?php echo $valor["ED03_NIVELSOPORTE"]?><br><br>
																										<strong>CLASIFICADOR : </strong><?php echo $valor["SIS07_CLASIFICADORDESCRIPCION"]?><br><br>
																										<strong>NUM ALUMNOS AFECTADOS : </strong><?php echo $valor["ED03_NUMALUMNOSAFECTADOS"]?><br><br>
																										<strong>NIVEL: </strong><?php echo $valor["ED03_NIVELDELPROGRAMA"]?><br><br>
																										<strong>MODULO : </strong><?php echo $valor["SIS05_CODIGOMODULO"]?><br><br>
																										<strong>NUM EJERCICIO : </strong><?php echo $valor["ED03_NUMEJERCICIO"]?><br><br>
																																															
																										<strong>DETALLE : </strong><br><?php echo nl2br($valor["ED03_DETALLETICKET"])?><br><br>
																										<?php
																										if(trim($valor["ED03_ARCHIVOADJUNTO"])!="")
																										{	
																										?>
																										<strong>ARCHIVO ADJUNTO : </strong><br>
																										
																										<strong><a href="<?php echo $valor["ED03_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor["ED03_NOMBREARCHIVOADJUNTO"]?></a></strong>
																										
																										<br><br>
																										
																										<?php
																										}
																										?>
																										<strong>SOLICITANTE : </strong><?php echo $valor["ED03_NOMBRESOLICITANTE"]?><br><br>
																										<strong>ULTIMA ACTUALIZACI&Oacute;N : </strong><?php echo $valor["FECHAULTIMAACTUALIZACION"]?><br><br>
																										<strong>ESTADO : </strong><?php echo $valor["ED03_ESTADO"]?><br><br>
																							
																									
																									
																									
																								</div>
																								<div class="modal-footer">
																									<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
																								</div>
																				
																		
																					</div>
																				</div>
																			</div>
																		</td>
															
																	
																	
																	
																	
																	</tr>
																	<?
																	}
																}
																?>
															</tbody>
														</table>
												</div>
											</div>
										</div>

								
								
									</div>
									<div class="tab-pane fade" id="profile-pills">
									
									
								
										 <div class="panel panel-success">
											<div class="panel-heading">
												Ultimas 10 Solicitudes Internas
											</div>
											<div class="panel-body" style="padding: 0px;">
												<div class="chat-widget-main">
				
														<table class="table table-hover">
															<thead>
																<tr>
																	<th>#</th>
																	<th>Fecha</th>
																	<th>Solicitante</th>
																	<th>Detalle</th>
																</tr>
															</thead>
															<tbody>
																<?php
																if(isset($datossolicitud))
																{
																	foreach($datossolicitud as $clave => $valor)
																	{
																	?>
																	<tr>
																		<td><?php echo $valor["ED02_SOLICITUDID"]?></td>
																		<td><?php echo $valor["ED02_FECHASOLICITUD"]?></td>
																		<td><?php echo $valor["ED02_NOMBRESOLICITANTE"]?></td>
																		<td><a href="#" data-toggle="modal" data-target="#myModal_sol_<?php echo $valor["ED02_SOLICITUDID"]?>">Detalle</a></td>
																		<td>
																			<div class="modal fade" id="myModal_sol_<?php echo $valor["ED02_SOLICITUDID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																				<div class="modal-dialog">
																					<div class="modal-content">
																							<div class="modal-header">
																									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
																									<h4 class="modal-title" id="myModalLabel"><strong>SOLICITUD NUMERO : <?php echo $valor["ED02_SOLICITUDID"]?></strong></h4>
																								</div>
																								<div class="modal-body">
																									
																										<strong>RBD : </strong><?php echo $valor["SIS03_LABORATORIOID"]?><br><br>
																										<strong>COLEGIO : </strong><?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?><br><br>
																										<strong>PRODUCTO : </strong><?php echo $valor["SIS04_PRODUCTOID"]?><br><br>
																										<strong>FECHA SOLICITUD : </strong><?php echo $valor["ED02_FECHASOLICITUD"]?><br><br>
																										<strong>DETALLE : </strong><br><?php echo nl2br($valor["ED02_DETALLESOLICITUD"])?><br><br>
																										<?php
																										if(trim($valor["ED02_ARCHIVOADJUNTO"])!="")
																										{	
																										?>
																										<strong>ARCHIVO ADJUNTO : </strong><br>
																										
																										<strong><a href="<?php echo $valor["ED02_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor["ED02_NOMBREARCHIVOADJUNTO"]?></a></strong>
																										
																										<br><br>
																										
																										<?php
																										}
																										?>
																										<strong>SOLICITANTE : </strong><?php echo $valor["ED02_NOMBRESOLICITANTE"]?><br><br>
																										<strong>FECHA INGRESO : </strong><?php echo $valor["FECHAINGRESO"]?><br><br>
																										<strong>ULTIMA ACTUALIZACI&Oacute;N : </strong><?php echo $valor["FECHAULTIMAACTUALIZACION"]?><br><br>
																										<strong>ESTADO : </strong><?php echo $valor["ED02_ESTADO"]?><br><br>
																							
																									
																									
																								</div>
																								<div class="modal-footer">
																									<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
																								</div>
																				
																		
																					</div>
																				</div>
																			</div>
																		</td>
															
																	
																	
																	
																	</tr>
																	<?
																	}
																}
																?>
															</tbody>
														</table>
												</div>
											</div>
										</div>

									
									
									</div>
									<div class="tab-pane fade" id="messages-pills">
									

									 <div class="panel panel-success">
											<div class="panel-heading">
												Ultimas 10 Atenciones T&eacute;cnicas
											</div>
											<div class="panel-body" style="padding: 0px;">
												<div class="chat-widget-main">
				
														<table class="table table-hover">
															<thead>
																<tr>
																	<th>#</th>
																	<th>Fecha</th>
																	<th>Solicitante</th>
																	<th>Detalle</th>
																</tr>
															</thead>
															<tbody>
																<?php
																if(isset($datosasistencias))
																{
																	foreach($datosasistencias as $clave => $valor)
																	{
																	?>
																	<tr>
																		<td><?php echo $valor["ED05_ASISTENCIAID"]?></td>
																		<td><?php echo $valor["ED05_FECHAINGRESO"]?></td>
																		<td><?php echo $valor["ED05_NOMBRESOLICITANTE"]?></td>
																		<td><a href="#" data-toggle="modal" data-target="#myModal_as_<?php echo $valor["ED05_ASISTENCIAID"]?>">Detalle</a></td>
																		<td>
																			<div class="modal fade" id="myModal_as_<?php echo $valor["ED05_ASISTENCIAID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																				<div class="modal-dialog">
																					<div class="modal-content">
																							<div class="modal-header">
																									<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
																									<h4 class="modal-title" id="myModalLabel"><strong>ASISTENCIA NUMERO : <?php echo $valor["ED05_ASISTENCIAID"]?></strong></h4>
																								</div>
																								<div class="modal-body">
																									
																									<strong>RBD : </strong><?php echo $valor["SIS03_LABORATORIOID"]?><br><br>
																									<strong>COLEGIO : </strong><?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?><br><br>
																									<strong>NUM ASISTENCIA : </strong><?php echo $valor["ED05_ASISTENCIAID"]?><br><br>
																									<strong>FECHA REGISTRO ASISTENCIA : </strong><?php echo $valor["ED05_FECHAINGRESO"]?><br><br>
																									<strong>FECHA A REALIZAR ASISTENCIA : </strong><?php echo $valor["FECHAREALIZARCE"]?><br><br>
																									
																									<strong>TELEFONO SOLICITANTE : </strong><?php echo $valor["ED05_TELEFONOSOLICITANTE"]?><br><br>
																									<strong>EMAIL SOLICITANTE : </strong><?php echo $valor["ED05_EMAILSOLICITANTE"]?><br><br>
																									<strong>PRIORIDAD : </strong><?php echo $valor["ED05_PRIORIDAD"]?><br><br>
																									<strong>TIPO CONTACTO : </strong><?php echo $valor["ED05_TIPOCONTACTO"]?><br><br>
																																														
																									<strong>DETALLE : </strong><br><?php echo nl2br($valor["ED05_DETALLEASISTENCIAREALIZAR"])?><br><br>
																									<?php
																									if(trim($valor["ED05_ARCHIVOADJUNTO"])!="")
																									{	
																									?>
																									<strong>ARCHIVO ADJUNTO : </strong><br>
																									
																									<strong><a href="<?php echo $valor["ED05_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor["ED05_NOMBREARCHIVOADJUNTO"]?></a></strong>
																									
																									<br><br>
																									
																									<?php
																									}
																									?>
																									<strong>SOLICITANTE : </strong><?php echo $valor["ED05_NOMBRESOLICITANTE"]?><br><br>
																									<strong>ULTIMA ACTUALIZACI&Oacute;N : </strong><?php echo $valor["FECHAULTIMAACTUALIZACION"]?><br><br>
																									<strong>ESTADO : </strong><?php echo $valor["ED05_ESTADO"]?><br><br>
																						
																								</div>
																								<div class="modal-footer">
																									<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
																								</div>
																				
																		
																					</div>
																				</div>
																			</div>
																		</td>
															
																	</tr>
																	<?
																	}
																}		
																?>
															</tbody>
														</table>
												</div>
											</div>
										</div>




									
									
									</div>
								</div>
							</div>
						</div>
	

		   </div>