<?php
$action=$this->layout()->action;
?>
<script type="text/javascript">
 
 
 	   function carga_listado(rbd,excel)
	   {


					if(excel=="1")
					{
				
				
							window.location.href="/Infcolegio/listar/Colegio/"+rbd+"/Excel/1";
				
				
					}else{
					
					
					
						var parametros = {
											"Colegio" : rbd,
											"Excel" : excel
										
										};
						
						$.ajax({
										data:  parametros,
										url:   '<?php echo $action?>', 
										type:  'post', 
										evalscripts : true,
										success:  function (response) { 
										
												$("#formulario").html(response);
															
										}
								});
				
					
					}

		}	


		//carga inicial
		carga_listado('10019','0');

</script>
<div id="formulario">
		
</div>