<?php
	
	if(isset($this->layout()->nombreapellido))
		$nombreapellido=$this->layout()->nombreapellido;

	if(isset($this->layout()->nivel))
		$nivel=$this->layout()->nivel;

	if(isset($this->layout()->niveldescripcion))
		$niveldescripcion=$this->layout()->niveldescripcion;

	if(isset($this->layout()->sector))
		$sector=$this->layout()->sector;
	
	if(isset($this->layout()->sectordescripcion))
		$sectordescripcion=$this->layout()->sectordescripcion;
	
?>

	<img src="/assets/img/user.png" class="img-thumbnail" />

	<div class="inner-text">
		<?php echo $nombreapellido;?>
	<br />
		<small><?php echo $sectordescripcion;?> / <?php echo $niveldescripcion;?></small>
	</div>
	
									
	
	