<?php
	
	if(isset($this->layout()->nivelid))
		$nivelid=$this->layout()->nivelid;

	if(isset($this->layout()->sectorid))
		$sectorid=$this->layout()->sectorid;


	if(isset($this->layout()->menu))
		$menu=$this->layout()->menu;

	if(isset($this->layout()->submenu))
		$submenu=$this->layout()->submenu;

	if(isset($this->layout()->permisos))
		$permisos=$this->layout()->permisos;


	$nivel_compuesto="N".$nivelid."ACC";
	$sector_compuesto=$sectorid;

	if(isset($sector_compuesto) && isset($permisos) && isset($permisos[$sector_compuesto]))
	$arreglo=$permisos[$sector_compuesto];
	
	
	$ACCESOS="";


	//cargamos accesos del usuario
	if(isset($arreglo))
	{
		
		foreach($arreglo as $clave => $valor)
		{
			if($clave==$nivel_compuesto)
			{
				$ACCESOS=$valor;
			}
		}

	}

?>
	<li>
		<div class="user-img-div" id="info-usuario">


		</div>
	</li>
	<?
		
		if($ACCESOS!="")
		{

			//vamos a recorrer los accesos
			$parte_accesos = explode("@@",$ACCESOS);
			foreach($parte_accesos as $clave => $valor)
			{
				$parte_permisos = explode("-",$valor);
				$matriz_link_accesos[$parte_permisos[0]]=$parte_permisos[0];
			}

	
		
			$parte_link = explode("/",$_SERVER['HTTP_REFERER']);
			$ELCONTROLLER=trim($parte_link[3]);
		
			foreach($menu as $clave => $valor)
			{
					$ELLINK="";
					$ELTEXTO="";
					$ELSUB=0;
					$ELID=0;
					$ELICONO="";
		
		
					foreach($valor as $clave2 => $valor2)
					{
						if($clave2=="LINK") $ELLINK=$valor2;
						if($clave2=="TEXTO") $ELTEXTO=$valor2;
						if($clave2=="SUB") $ELSUB=$valor2;
						if($clave2=="ID") $ELID=$valor2;
						if($clave2=="ICONO") $ELICONO=$valor2;
					
					}


					//si tiene acceso
					if(isset($matriz_link_accesos[$ELID]))
					{

		
									if($ELSUB==0)
									{
									?>
									<li>
										<a <?php if($ELCONTROLLER==trim(str_replace('/', '',$ELLINK))){?> class="active-menu" <?php } ?> href="<?php echo $ELLINK?>"><i class="<?php echo $ELICONO;?>"></i><?php echo $ELTEXTO?></a>
									</li>
									<?
									}else{
									?>			
						
													<li>
														<a href="<?php echo $ELLINK?>"><i class="<?php echo $ELICONO;?>"></i><?php echo $ELTEXTO?><span class="fa arrow"></span></a>
														 <ul class="nav nav-second-level">
																	<?
																		foreach($submenu as $clave3 => $valor3)
																		{
																				$ELLINK2="";
																				$ELTEXTO2="";
																				$ELPADRE="";
																				$ELICONO2="";
																				$ELID2=0;
					
																			
																				foreach($valor3 as $clave3 => $valor3)
																				{
																					if($clave3=="LINK") $ELLINK2=$valor3;
																					if($clave3=="TEXTO") $ELTEXTO2=$valor3;
																					if($clave3=="PADRE") $ELPADRE=$valor3;
																					if($clave3=="ICONO") $ELICONO2=$valor3;
																					if($clave3=="ID") $ELID2=$valor3;
					
																				}
																	
																	
																				if($ELPADRE==$ELID && isset($matriz_link_accesos[$ELID2]))
																				{
																	
																					?>
																					<li>
																						<a  <?php if($ELCONTROLLER==trim(str_replace('/', '',$ELLINK2))){?> class="active-menu" <?php } ?> href="<?php echo $ELLINK2;?>"><i class="<?php echo $ELICONO2;?>"></i><?php echo $ELTEXTO2;?></a>
																					</li>
																					<?
																				}
																	
																		}				
																				
																	?>
														</ul>
													</li>
						
									<?			
									}
						
						}//si tiene acceso
			
			}	
		
	
	}//si existen accesos
	
	?>
	<!--
	<a href="panel-tabs.html"><i class="fa fa-toggle-on"></i>Tabs & Panels</a>
	<a class="active-menu" href="notification.html"><i class="fa fa-bell "></i>Notifications</a>
	<a href="progress.html"><i class="fa fa-circle-o "></i>Progressbars</a>
	<a href="buttons.html"><i class="fa fa-code "></i>Buttons</a>
	<a href="icons.html"><i class="fa fa-bug "></i>Icons</a>
	<a href="wizard.html"><i class="fa fa-bug "></i>Wizard</a>
	<a href="typography.html"><i class="fa fa-edit "></i>Typography</a>
	<a href="grid.html"><i class="fa fa-eyedropper "></i>Grid</a>
	-->