<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-DESK / Recordar Clave</title>

    <!-- BOOTSTRAP STYLES-->
    <link href="/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="/assets/css/font-awesome.css" rel="stylesheet" />
    <!-- GOOGLE FONTS-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
	
	<!-- JQUERY SCRIPTS -->
	<script src="/assets/js/jquery-1.10.2.js"></script>

	<script type="text/javascript">
 
 	
	   var emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$";
 
 
	   function accion_recordar()
	   {
	
				
				if($("#email").val().length<5 || !$("#email").val().match(emailPattern))
				{
					alert("Debe Ingresar Correctamente un E-mail");
					$("#email").focus();
					return false;		
				} 
			
	
	
				var parametros = {
									"email" : $("#email").val()
								};
				
				$.ajax({
								data:  parametros,
								url:   '/Login/recordarclaveprocess', 
								type:  'post', 
								evalscripts : true,
								success:  function (response) { 
								
								
										var str=response;
										var res = str.split("|");
								
										if(res[0]=='OK')
										{
												$("#divNotificacionesRecordar").html("<div class='panel-body'><div class='alert alert-danger alert-dismissable'><u>Tus datos para ingresar son</u> : <br><br><strong>Usuario :</strong> "+res[1]+" <br> <strong>Password :</strong> "+res[2]+" </div></div>");
												$("#email").val("");
												notificacion();
										
										}else{
												$("#divNotificacionesRecordar").html("<div class='panel-body'><div class='alert alert-danger alert-dismissable'>"+res[1]+"</div></div>");
											}				
								}
						});
						
	

 	   }	
	
	
	
		$(document).keypress(function(event){
			var keycode = (event.keyCode ? event.keyCode : event.which);
			if(keycode == '13'){
				document.getElementById("envia_accion_recordar").click();
			}
		});




    function notificacion() {

        if (Notification) {

            if (Notification.permission !== "granted") {

                Notification.requestPermission()

            }
            var title = "E-DESK"
            var extra = {

                icon: "http://edesk.e-mat.cl/assets/img/user.png",
                body: "Nueva clave generada para E-DESK"

            }
            var noti = new Notification( title, extra)
            noti.onclick = {

   		 
            }
            noti.onclose = {

   		
            }
            setTimeout( function() { noti.close() }, 10000)

        }

    }


	</script>

	
</head>
<body style="background-color: #E2E2E2;">
    <div class="container">
        <div class="row text-center " style="padding-top:100px;">
            <div class="col-md-12">
                <img src="/assets/img/logo_edesk.png" />
            </div>
        </div>
         <div class="row ">
               
                <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
                           
                            <div class="panel-body">
                                <form role="form">
                                    <hr />
									<div id="divNotificacionesRecordar">
									</div>
								
                                    <h5>Ingresa tu e-mail registrado</h5>
                                       <br />
                                       <div class="form-group input-group">
                                            <span class="input-group-addon"><i class="fa fa-envelope fa-fw"  ></i></span>
                                            <input type="text" class="form-control"  placeholder="Tu e-mail" onFocus="$('#email').attr('placeholder','').placeholder()" id="email" name="email"/>
                                        </div>
                                    	
										<a href="#" onClick="accion_recordar();" class="btn btn-primary " id="envia_accion_recordar">Recuperar</a>
										
										<hr />
										¿ Recuperaste tu clave ? <a href="/" >CLICK AQUI</a> 
									</form>
                            </div>
                           
                        </div>
                
                
        </div>
    </div>

</body>
</html>