<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>E-DESK</title>
	<?php
	if($_SERVER["REQUEST_URI"]=="/Fichacolegio" || 
	   $_SERVER["REQUEST_URI"]=="/Usuario"  || 
	   $_SERVER["REQUEST_URI"]=="/Solicitud"  || 
	   $_SERVER["REQUEST_URI"]=="/Incidente"  || 
	   $_SERVER["REQUEST_URI"]=="/Asistencia"){
	 ?>
	<?php
	}
	?>

    <!-- BOOTSTRAP STYLES-->
    <link href="/assets/css/bootstrap.css" rel="stylesheet" />
	<style>
	
		dialog {
		visibility: hidden;
		transform: scale(0.1);
		transition: transform 200ms;
		}

		dialog.dialog-scale {
			visibility: visible;
			transform: scale(1);
		}

		
	</style>
	
	
	
    <!-- GOOGLE FONTS-->
	<link href="/assets/css/open-sans.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLES-->
    <link href="/assets/css/font-awesome.css" rel="stylesheet" />
    <!--CUSTOM BASIC STYLES-->
    <link href="/assets/css/basic.css" rel="stylesheet" />
    <!--CUSTOM MAIN STYLES-->
    <link href="/assets/css/custom.css" rel="stylesheet" />
	<!-- JQUERY SCRIPTS -->
	<script src="/assets/js/jquery-1.10.2.js"></script>

	
	<!-- date-range-picker -->
	<script src="/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
	<link href="/assets/css/jquery-ui.css" rel="stylesheet">
	<script src="/assets/js/jquery-ui.js"></script>

	<script language="JavaScript" type="text/javascript">
	
	
	
	
		
		function trae_menu()
		{
		
			var parametros = {};
	
			$.ajax({
						data:  parametros,
						url:   '/Login/menuperfil', 
						type:  'post', 
						success:  function (response) { 
					
								$("#main-menu").html(response);
								trae_datos_usuarios();	
						}
					});
		}
	
	
		function trae_datos_usuarios()
		{
		
				var parametros = {};
		
				$.ajax({
							data:  parametros,
							url:   '/Login/infousuario', 
							type:  'post', 
							success:  function (response) { 
						
									$("#info-usuario").html(response);
									trae_notificaciones();
						
							}
						});
		
		}					
	

		function trae_notificaciones()
		{
		
				var parametros = {tipo:'0'};
		
				$.ajax({
							data:  parametros,
							url:   '/Login/notificacion', 
							type:  'post', 
							evalscripts : true,
							success:  function (response) { 
						
										 $("#idNumNotificaciones").html(response);
						
										setTimeout(function(){
				
													trae_notificaciones();
				
										},60000); 
										
									  

							}
						});
		
		}					


		trae_menu();


			
	
	</script>

</head>
<body>
	
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/index.php">E-DESK</a>
            </div>

            <div class="header-right">

				<div id="idNumNotificaciones"></div>

            </div>

        </nav>
        <!-- /. NAV TOP  -->

        <nav class="navbar-default navbar-side" role="navigation">

            <div class="sidebar-collapse">

						<ul class="nav" id="main-menu">
		
						
						</ul>


            </div>

        </nav>
        <!-- /. NAV SIDE  -->
       

		<div id="page-wrapper">
			   
			   
				<div id="page-inner">
					





					<?php echo $this->layout()->content; ?>    








				</div>
				<!-- /. PAGE INNER  -->
			</div>
			<!-- /. PAGE WRAPPER  -->
		</div>
		<!-- /. WRAPPER  -->


	     <div id="footer-sec">
        	&copy; 2019 Compumat.cl | Diseñado por : <a href="http://www.compumat.cl/" target="_blank">Compumat.cl</a>
    	</div>
		<!-- /. FOOTER  -->
		
		<!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
		<!-- BOOTSTRAP SCRIPTS -->
		<script src="/assets/js/bootstrap.js"></script>
	 	<!-- METISMENU SCRIPTS -->
		<script src="/assets/js/jquery.metisMenu.js"></script>
	    <!-- CUSTOM SCRIPTS -->
		<script src="/assets/js/custom.js"></script> 

</body>
</html>