<?php
	
	//inicio si hay solicitud	
	//////////////////////////
	
	if(isset($this->layout()->solicitudid))
		$solicitudid=$this->layout()->solicitudid;
	
	if(isset($this->layout()->incidenteid))
		$incidenteid=$this->layout()->incidenteid;

	if(isset($this->layout()->LABORATORIOID))
		$LABORATORIOID=$this->layout()->LABORATORIOID;

	if(isset($this->layout()->LABORATORIODESCRIPCION))
		$LABORATORIODESCRIPCION=$this->layout()->LABORATORIODESCRIPCION;

	if(isset($this->layout()->PRODUCTOID))
		$PRODUCTOID=$this->layout()->PRODUCTOID;

	if(isset($this->layout()->DETALLESOLICITUD))
		$DETALLESOLICITUD=$this->layout()->DETALLESOLICITUD;

	if(isset($this->layout()->NOMBRESOLICITANTE))
		$NOMBRESOLICITANTE=$this->layout()->NOMBRESOLICITANTE;
	
	//fin si hay solicitud	
	//////////////////////////
	
	
	
	if(isset($this->layout()->datoscolegio))
		$datoscolegio=$this->layout()->datoscolegio;

	
	if(isset($this->layout()->datosusuarios))
		$datosusuarios=$this->layout()->datosusuarios;
	

?>
	<script type="text/javascript">
		
		   var emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$";
		   var match= ["application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","image/jpeg","image/png","image/jpg","image/gif","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel","application/pdf"];
			
		
		   $(document).ready(function() {
		
		
		
				$("#archivo").change(function() {
			
					var file = this.files[0];
					var imagefile = file.type;
					
					if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2]) || (imagefile==match[3]) || (imagefile==match[4]) || (imagefile==match[5]) || (imagefile==match[6]) || (imagefile==match[7]) || (imagefile==match[8]) || (imagefile==match[9]) || (imagefile==match[10]) || (imagefile==match[11]))){
						alert('Por favor seleccione un archivo del tipo (JPEG / JPG / PNG / GIF / TXT / DOC / XLS / PDF / PPT).');
						$("#archivo").val('');
						return false;
					}
			
				});
		
		
		
				$("#calendario").datepicker({dateFormat: 'dd/mm/yy'});
	 

				$("#btn_guardar").click(function(){
	
	
					var val = $("#colegio").val();
					
					
					<?php 
					if(!isset($LABORATORIOID) || $LABORATORIOID=="")
					{ 
					?>
					var obj = $("#colegio_lista").find("option[value='" + val + "']");
					
					if(obj != null && obj.length > 0)
					{
						//OK  
					}else{
							alert("Debe Ingresar Correctamente el Colegio Asociado");
							$("#colegio").focus();
							return false;
						 }	
					<?php 
					}
					?>
					
					
					if($("#calendario").val().length<10)
					{
						alert("Debe Ingresar la Fecha a Realizar Asistencia");
						$("#calendario").focus();
						return false;
					} 
					
					
					if($("#nombreapellido").val().length<5)
					{
						alert("Debe Ingresar Correctamente Nombre y Apellido del Contacto");
						$("#nombreapellido").focus();
						return false;
					} 
					
					if($("#telefono").val().length<5)
					{
						alert("Debe Ingresar Correctamente el Telefono del Contacto");
						$("#telefono").focus();
						return false;
					} 
					
					
					
						
					if($("#email").val().length>0 && !$("#email").val().match(emailPattern))
					{
						alert("Debe Ingresar Correctamente un E-mail");
						$("#email").focus();
						return false;		
					} 
					
				
					if(!$("#prioridad").val())
					{
						alert("Debe Seleccionar Prioridad");
						$("#prioridad").focus();
						return false;
					}			
	
					if($("#detalle").val().length<5)
					{
						alert("Debe Ingresar el Detalle de la Asistencia");
						$("#detalle").focus();
						return false;
					} 
		
					if(!$("#tipocontacto").val())
					{
						alert("Debe Seleccionar Tipo Contacto");
						$("#tipocontacto").focus();
						return false;
					}			

		

					if (!confirm("Desea Guardar la Asistencia?")) 
					{
					
						return false;
					
					} else {
					
							grabar();
										
					}
					
	
				});
			}); 
	
	
	
			function grabar()
			{
	
				var file_data = $('#archivo').prop('files')[0];   
				var form_data = new FormData();                  
				form_data.append('file', file_data);

				form_data.append('colegio',$("#colegio").val());
				form_data.append('calendario', $("#calendario").val());
				form_data.append('nombreapellido', $("#nombreapellido").val());
				form_data.append('telefono', $("#telefono").val());
				form_data.append('email', $("#email").val());
				form_data.append('prioridad', $("#prioridad").val());
				form_data.append('detalle', $("#detalle").val());
				form_data.append('tipocontacto', $("#tipocontacto").val());
				form_data.append('archivo', $("#archivo").val());
				form_data.append('derivado', $("#derivado").val());
				form_data.append('estado', $("#estado").val());
				form_data.append('accion', 'grabar');
				<?php
				if(isset($solicitudid) && $solicitudid!="")
				{
				?>
				form_data.append('solicitudid', '<?php echo $solicitudid?>');
				<?php
				}
				if(isset($incidenteid) && $incidenteid!="")
				{
				?>
				form_data.append('incidenteid', '<?php echo $incidenteid?>');
				<?php
				}
				?>
				
				$.ajax({
								url:   '/Asistencia/agregarasistenciaprocess', 
								dataType: 'text',  
								cache: false,
								contentType: false,
								processData: false,
								data: form_data,                         
								type: 'post',
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>Procesando solicitud..</div></div>");
														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
													$("#divNotificaciones").html("<div class='panel panel-success'><div class='panel-heading'>Datos almacenados correctamente</div></div>");
													$('#volver_bot').focus();
													//limpia formulario
													$('#oForm').trigger("reset");
													$("#detalle").val("");
											
											}else{
													
													$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>"+res[1]+"</div></div>");
												
											}
										
								}
						});
		  
			} 	
	
	
	
	
	
	</script>


 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
						   </div>	
				
				
							<div class="panel panel-default">
				
									<div class="panel-heading">
                                        <button type="button" class="btn btn btn-default">INGRESO ASISTENCIA</button>
										<?php
										if(isset($solicitudid) && $solicitudid!="")
										{
										?>
												<a href="/Solicitud"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
										<?php
										}else{
									
												if(isset($incidenteid) && $incidenteid!="")
												{
				
												?>
												<a href="/Incidente"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
												<?php
									
												}else{
										?>
												<a href="/Asistencia"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
										<?php
												}
										}
										?>
							
							        </div>
									
									
									<div class="panel-body">
				
											 
											 
															<form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
																 
																		<div class="form-group">
																			<label>Colegio (*)</label>
																			<?php 
																			if(isset($LABORATORIOID) && $LABORATORIOID!=""){ 
																			?>
																				<input type="hidden" name="colegio" id="colegio" value="<?php echo $LABORATORIOID?> | <?php echo $LABORATORIODESCRIPCION?>">
																				<br>
																				<?php if(isset($LABORATORIODESCRIPCION) && $LABORATORIODESCRIPCION!="") echo $LABORATORIODESCRIPCION;?>
																			<?php
																			}else{
																			?>
																			
																				<input list="colegio_lista" class="form-control" id="colegio">
																				<datalist id="colegio_lista">
																					<?php
																					if(isset($datoscolegio))
																					{
																						foreach($datoscolegio as $clave => $valor)
																						{
																						?>
																							<option value="<?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?>">
																						<?
																						}
																					}		
																					?>
																				</datalist>

																			<?php
																			}
																			?>																

																			
																
																		</div>
																	  
																	   <div class="form-group">
																			<label>Fecha a Realizar Asistencia (*)</label>
																			<input type="text" class="form-control" id="calendario" readonly="readonly">
																	   </div>
																	  
																
																	   <div class="form-group">
																			<label>Nombre Solicitante (*)</label>
																			<input class="form-control" type="text" id="nombreapellido" maxlength="100"  name="nombreapellido" value="<?php if(isset($NOMBRESOLICITANTE) && $NOMBRESOLICITANTE!="") echo $NOMBRESOLICITANTE;?>">
																	   </div>
																	 
																	   <div class="form-group">
																			<label>Tel&eacute;fono Solicitante (*)</label>
																			<input class="form-control" type="text" id="telefono" maxlength="50"  name="telefono">
																	   </div>
																	  
																	   <div class="form-group">
																			<label>E-mail Solicitante</label>
																			<input class="form-control" type="text" id="email" maxlength="100"  name="email">
																	   </div>
																	  
																		<div class="form-group">
																			<label>Prioridad (*)</label>
																			<select class="form-control" id="prioridad" name="prioridad">
																				<option value="1">ALTA</option>
																				<option value="0">BAJA</option>
																			</select>
																		</div>
																												  
																		<div class="form-group">
																			<label>Detalle Asistencia (*)</label>
																			<textarea class="form-control" rows="5" id="detalle" name="detalle"><?php if(isset($DETALLESOLICITUD) && $DETALLESOLICITUD!="") echo $DETALLESOLICITUD;?></textarea>
																		</div>
															  
															  
																		<div class="form-group">
																			<label>Tipo Contacto (*)</label>
																			<select class="form-control" id="tipocontacto" name="tipocontacto">
																				<option value="TELEFONO">TELEFONO</option>
																				<option value="ANYDESK">ANYDESK</option>
																				<option value="TERRENO">TERRENO</option>
																			</select>
																		</div>
																		
														
																			 
																		 <div class="form-group">
																			<label class="control-label col-lg-4">Adjunto</label>
																			<div class="">
																				 <input type="file" name="archivo" id="archivo" class="btn btn-info">
																			</div>
																		</div>
																		 
														
														
														 				<div class="form-group">
																			<label>Derivado a: (*)</label>
																			<select class="form-control" id="derivado" name="derivado">
																				<?php
																				if(isset($datosusuarios))
																				{
																					foreach($datosusuarios as $clave => $valor)
																					{
																					?>
																						<option value="<?php echo $valor["ED01_USUARIOID"]?>"><?php echo $valor["ED01_NOMBREAPELLIDO"]?></option>
																					<?
																					}
																				}		
																				?>
																			</select>
																		</div>
																	  
														
														
																		<div class="form-group">
																			<label>Estado (*)</label>
																			<select class="form-control" id="estado" name="estado">
																				<option value="PENDIENTE">PENDIENTE</option>
																				<option value="DERIVADO">DERIVADO</option>
																				<option value="RESUELTO">RESUELTO</option>
																				<option value="MEJORA-FUTURA">MEJORA-FUTURA</option>
																			</select>
																		</div>
															
																					
																	  <button type="button" class="btn btn-info" id="btn_guardar">Guardar</button>
				
				
				
															</form>
        			                         
										</div>
				
								</div>
				
					 </div>
				 
				 
				 </div>

 </div>