<?php
	
	if(isset($this->layout()->datoscolegio))
		$datoscolegio=$this->layout()->datoscolegio;

	if(isset($this->layout()->datosusuarios))
		$datosusuarios=$this->layout()->datosusuarios;
	
	
		$ASISTENCIAID=$this->layout()->ASISTENCIAID;
		$LABORATORIOID=$this->layout()->LABORATORIOID;
		$LABORATORIODESCRIPCION=$this->layout()->LABORATORIODESCRIPCION;
		$FECHAASISTENCIA=$this->layout()->FECHAASISTENCIA;
		$NOMBRESOLICITANTE=$this->layout()->NOMBRESOLICITANTE;
		$TELEFONOSOLICITANTE=$this->layout()->TELEFONOSOLICITANTE;
		$EMAILSOLICITANTE=$this->layout()->EMAILSOLICITANTE;
		$PRIORIDAD=$this->layout()->PRIORIDAD;
		$DETALLEASISTENCIAREALIZAR=$this->layout()->DETALLEASISTENCIAREALIZAR;
		$TIPOCONTACTO=$this->layout()->TIPOCONTACTO;
		$ARCHIVOADJUNTO=$this->layout()->ARCHIVOADJUNTO;
		$NOMBREARCHIVOADJUNTO=$this->layout()->NOMBREARCHIVOADJUNTO;
		$TIPOARCHIVOADJUNTO=$this->layout()->TIPOARCHIVOADJUNTO;
		$FECHAREALIZARCE=$this->layout()->FECHAREALIZARCE;
		$ESTADO=$this->layout()->ESTADO;
		$USUARIOSELECCIONADO=$this->layout()->USUARIOSELECCIONADO;
	
	
?>

<script type="text/javascript">
		
	           var emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+.[a-zA-Z]{2,4}$";
			   var match= ["application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","image/jpeg","image/png","image/jpg","image/gif","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel","application/pdf"];
			   var val = $("#colegio").val("<?php echo $LABORATORIOID?> | <?php echo $LABORATORIODESCRIPCION?>");
		
		
				$("#archivo").change(function() {
			
					var file = this.files[0];
					var imagefile = file.type;
					
					if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2]) || (imagefile==match[3]) || (imagefile==match[4]) || (imagefile==match[5]) || (imagefile==match[6]) || (imagefile==match[7]) || (imagefile==match[8]) || (imagefile==match[9]) || (imagefile==match[10]) || (imagefile==match[11]))){
						alert('Por favor seleccione un archivo del tipo (JPEG / JPG / PNG / GIF / TXT / DOC / XLS / PDF / PPT).');
						$("#archivo").val('');
						return false;
					}
			
				});
		
		
		
				$("#calendario").datepicker({dateFormat: 'dd/mm/yy'});
	 
				
				function valida_grabar_asistencia()
				{
		
								
							val = $("#colegio").val();
							var obj = $("#colegio_lista").find("option[value='" + val + "']");
							
							if(obj != null && obj.length > 0)
							{
								//OK  
							}else{
									alert("Debe Ingresar Correctamente el Colegio Asociado");
									$("#colegio").focus();
									return false;
								 }	
								
							
							
											
							if($("#calendario").val().length<10)
							{
								alert("Debe Ingresar la Fecha a Realizar Asistencia");
								$("#calendario").focus();
								return false;
							} 
							
							if($("#nombreapellido").val().length<5)
							{
								alert("Debe Ingresar Correctamente Nombre y Apellido del Contacto");
								$("#nombreapellido").focus();
								return false;
							} 
					
							if($("#telefono").val().length<5)
							{
								alert("Debe Ingresar Correctamente el Telefono del Contacto");
								$("#telefono").focus();
								return false;
							} 
								
							if($("#email").val().length>0 && !$("#email").val().match(emailPattern))
							{
								alert("Debe Ingresar Correctamente un E-mail");
								$("#email").focus();
								return false;		
							} 
							
						
							if(!$("#prioridad").val())
							{
								alert("Debe Seleccionar Prioridad");
								$("#prioridad").focus();
								return false;
							}			
			
							if($("#detalle").val().length<5)
							{
								alert("Debe Ingresar el Detalle de la Asistencia");
								$("#detalle").focus();
								return false;
							} 
				
							if(!$("#tipocontacto").val())
							{
								alert("Debe Seleccionar Tipo Contacto");
								$("#tipocontacto").focus();
								return false;
							}			
		
					
							if (!confirm("Desea Guardar la Asistencia?")) 
									{
							
								return false;
							
							} else {
							
									grabar_asistencia();
												
							}
							
		
			
			}
	
	
	
	
			function grabar_asistencia()
			{
	
				
				var file_data = $('#archivo').prop('files')[0];   
				var form_data = new FormData();                  
				form_data.append('file', file_data);
				
				form_data.append('asistenciaid',$("#asistenciaid").val());
				form_data.append('colegio',$("#colegio").val());
				form_data.append('calendario', $("#calendario").val());
				form_data.append('nombreapellido', $("#nombreapellido").val());
				form_data.append('telefono', $("#telefono").val());
				form_data.append('email', $("#email").val());
				form_data.append('prioridad', $("#prioridad").val());
				form_data.append('detalle', $("#detalle").val());
				form_data.append('tipocontacto', $("#tipocontacto").val());
				form_data.append('archivo', $("#archivo").val());
				form_data.append('derivado', $("#derivado").val());
				form_data.append('estado', $("#estado").val());
				form_data.append('accion', 'grabar');
				
				
				$.ajax({
								url:   '/Asistencia/editarasistenciaprocess', 
								dataType: 'text',  
								cache: false,
								contentType: false,
								processData: false,
								data: form_data,                         
								type: 'post',
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel-body'><h4 class='alert alert-info' style='line-height:50px;'>Procesando asistencia..</h4></div>");
														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
												$("#formulario").html("<div class='panel-body' id='volver_frame'><a href='/Asistencia'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a><h4 class='alert alert-info' style='line-height:50px;'>Datos almacenados correctamente</h4></div>");
												$('#volver_bot').focus();
									
											}else{
												
													$("#formulario").html("<div class='panel-body' id='volver_frame'><a href='/Asistencia'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a><h4 class='alert alert-info' style='line-height:50px;'>"+res[1]+"</h4></div>");
													$('#volver_bot').focus();
										
											}
										
								}
						});
		  
			} 	
	
	

</script>
				
	
 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
							    <div class='panel-body'>
									<a href="/Asistencia"><button type="button" class="btn btn-danger">Volver</button></a>
                           		</div>
						   </div>	
				
				
							<div class="panel panel-danger">
				
									<div class="panel-heading">
                                       <strong>EDITAR ASISTENCIA</strong>
                                    </div>
                                    <div class="panel-body">
				
										
										
				                            <form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
												 
												    <input type="hidden" id="asistenciaid" name="asistenciaid" value="<?php echo $ASISTENCIAID?>">
												 	<div class="form-group">
                                                        <label>Colegio (*)</label>

                                                        <input list="colegio_lista" class="form-control" id="colegio">
														<datalist id="colegio_lista">
															<?php
															if(isset($datoscolegio))
															{
																foreach($datoscolegio as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?>" <?php if($LABORATORIOID==$valor["SIS03_LABORATORIOID"]) echo "selected='selected'"?>>
																<?
																}
															}		
															?>
														</datalist>
														
											
												  </div>
                                                  
												  
													   <div class="form-group">
															<label>Fecha a Realizar Asistencia (*)</label>
															<input type="text" class="form-control" id="calendario" readonly="readonly" value="<?php echo $FECHAASISTENCIA?>">
													   </div>
	
													  
													   <div class="form-group">
															<label>Nombre Solicitante (*)</label>
															<input class="form-control" type="text" id="nombreapellido" maxlength="100"  name="nombreapellido" value="<?php echo $NOMBRESOLICITANTE?>">
													   </div>
												 
													   <div class="form-group">
															<label>Tel&eacute;fono Solicitante (*)</label>
															<input class="form-control" type="text" id="telefono" maxlength="50"  name="telefono" value="<?php echo $TELEFONOSOLICITANTE?>">
													   </div>
													  
													   <div class="form-group">
															<label>E-mail Solicitante</label>
															<input class="form-control" type="text" id="email" maxlength="100"  name="email" value="<?php echo $EMAILSOLICITANTE?>">
													   </div>
													  
														<div class="form-group">
															<label>Prioridad (*)</label>
															<select class="form-control" id="prioridad" name="prioridad">
																<option value="1" <?php if($PRIORIDAD=="1") echo "selected"?>>ALTA</option>
																<option value="0" <?php if($PRIORIDAD=="0") echo "selected"?>>BAJA</option>
															</select>
														</div>
										
														<div class="form-group">
															<label>Detalle Asistencia (*)</label>
															<textarea class="form-control" rows="5" id="detalle" name="detalle"><?php echo $DETALLEASISTENCIAREALIZAR?></textarea>
														</div>
										   
														<div class="form-group">
															<label>Tipo Contacto (*)</label>
															<select class="form-control" id="tipocontacto" name="tipocontacto">
																<option value="TELEFONO" <?php if($TIPOCONTACTO=="TELEFONO") echo "selected"?>>TELEFONO</option>
																<option value="ANYDESK" <?php if($TIPOCONTACTO=="ANYDESK") echo "selected"?>>ANYDESK</option>
																<option value="TERRENO" <?php if($TIPOCONTACTO=="TERRENO") echo "selected"?>>TERRENO</option>
															</select>
														</div>
														
															 
														 <div class="form-group">
															<label class="control-label col-lg-4">Adjunto </label>
															<div class="">
																 <input type="file" name="archivo" id="archivo" class="btn btn-info">
																 <?php
																 if(trim($NOMBREARCHIVOADJUNTO)!="")
																 {
																 ?>
																 <br>
																 <strong>Archivo actual : <a href="<?php echo $ARCHIVOADJUNTO?>" target="_blank"><?php echo $NOMBREARCHIVOADJUNTO?></a></strong>
																 <?php
																 }
																 ?>
															</div>
														</div>
														 
														 
														 <div class="form-group">
															<label>Derivado a: (*)</label>
															<select class="form-control" id="derivado" name="derivado">
																<?php
																if(isset($datosusuarios))
																{
																	foreach($datosusuarios as $clave => $valor)
																	{
																	?>
																		<option value="<?php echo $valor["ED01_USUARIOID"]?>" <?php if($USUARIOSELECCIONADO==$valor["ED01_USUARIOID"]) echo "selected"?>><?php echo $valor["ED01_NOMBREAPELLIDO"]?></option>
																	<?
																	}
																}		
															
															
															
																?>
															</select>
														</div>
													  														 
															 
														 <div class="form-group">
															<label>Estado (*)</label>
															<select class="form-control" id="estado" name="estado">
																<option value="PENDIENTE" <?php if($ESTADO=="PENDIENTE") echo "selected"?>>PENDIENTE</option>
																<option value="DERIVADO" <?php if($ESTADO=="DERIVADO") echo "selected"?>>DERIVADO</option>
																<option value="RESUELTO" <?php if($ESTADO=="RESUELTO") echo "selected"?>>RESUELTO</option>
																<option value="MEJORA-FUTURA" <?php if($ESTADO=="MEJORA-FUTURA") echo "selected"?>>MEJORA-FUTURA</option>
															</select>
														</div>
																		
													  <button type="button" class="btn btn-info" id="btn_guardar" onclick="valida_grabar_asistencia()">Guardar</button>



										    </form>
                                  
								      
								  </div>

							</div>
				
					 </div>
				 </div>

 </div>