<?php
if(isset($this->layout()->busqueda))
		$busqueda=$this->layout()->busqueda;
else	
		$busqueda="DERIVADO";
?>
<script type="text/javascript">
 
       
   	 	function graba_lectura_notificaciones(valores)
		{
		
				var parametros = {
								 tipo:'3',
								 concepto:'asistencia',
								 valores:valores
								 };
		
				$.ajax({
							data:  parametros,
							url:   '/Login/notificacion', 
							type:  'post', 
							evalscripts : true,
							success:  function (response) { 
						
						
							}
						});
		
		}					

	   
	   
	   
	   
	   function accion_eliminar(asistenciaid)
	   {

				if (!confirm("Desea Eliminar los Datos de la Asistencia?")) 
				{
				
					return false;
				
				} else {
				
							var parametros = {
												"asistenciaid" : asistenciaid
											};
							
							$.ajax({
											data:  parametros,
											url:   '/Asistencia/eliminarasistencia', 
											type:  'post', 
											evalscripts : true,
											success:  function (response) { 
											
													$("#formulario").html("<div class='panel panel-success'><div class='panel-heading' id='volver_frame'>"+response+"<br><br><a href='/Asistencia'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a></div></div>");
													$('#volver_bot').focus();
																
											}
									});
									
				}

 	   }	
 
 	   function carga_editar(asistenciaid)
	   {

					var parametros = {
										"asistenciaid" : asistenciaid
									};
					
					$.ajax({
									data:  parametros,
									url:   '/Asistencia/editarasistencia', 
									type:  'post', 
									evalscripts : true,
									success:  function (response) { 
									
											$("#formulario").html(response);
														
									}
							});

		}	   



 	   function carga_pagina_asistencia(pagina,busqueda)
	   {

					var parametros = {
										"pagina" : pagina,
										"busqueda" : busqueda 
									};
					
					$.ajax({
									data:  parametros,
									url:   '/Asistencia/listarasistencias', 
									type:  'post', 
									evalscripts : true,
									success:  function (response) { 
									
											$("#formulario").html(response);
														
									}
							});

		}	


		//carga inicial
		carga_pagina_asistencia('1','<?php echo $busqueda?>');
</script>
<div id="formulario">
		
</div>						
