<?php
	
	if(isset($this->layout()->acceso_funcionalidades))
		$acceso_funcionalidades=$this->layout()->acceso_funcionalidades;
		
	if(isset($this->layout()->datos_seguimiento))
		$datos_seguimiento=$this->layout()->datos_seguimiento;
		
	if(isset($this->layout()->datosasistencias))
		$datosasistencias=$this->layout()->datosasistencias;
	
	if(isset($this->layout()->total_filas))
		$total_filas=$this->layout()->total_filas;
	
	if(isset($this->layout()->pagina))
		$pagina=$this->layout()->pagina;

	if(isset($this->layout()->num_paginas))
		$num_paginas=$this->layout()->num_paginas;

	if(isset($this->layout()->registro_ini))
		$registro_ini=$this->layout()->registro_ini;

	if(isset($this->layout()->registro_fin))
		$registro_fin=$this->layout()->registro_fin;
	
	if(isset($this->layout()->busqueda))
		$busqueda=$this->layout()->busqueda;
		
	if(isset($this->layout()->datos_derivados))
		$datos_derivados=$this->layout()->datos_derivados;
		
	
	if($total_filas < $registro_fin)
	   $ULTIMO_REG=$total_filas;
	else   
	   $ULTIMO_REG=$registro_fin;
	
	
?>
<script type="text/javascript">
 
	   
	   $("#realizar_busqueda_asistencias").click( function()
       {
         	if($("#busqueda").val()!="")
			{
				carga_pagina_asistencia('1',$("#busqueda").val());
		  	}
		 }
        );
	   
   
	   
</script>
	   
<div class="col-md-12">
		   
		   <div id="divNotificacionesCentral">
		   </div>									 
						
						
						
		<div class="panel-footer">
			<div class="input-group">
				<input type="text" name="busqueda" id="busqueda" class="form-control" value="<?php echo $busqueda?>" placeholder="" data-toggle="tooltip" title="Puedes buscar por : RBD / NUM ASISTENCIA / ESTADO (PEN - DER - RES - MEJ - GES)" />
				<span class="input-group-btn">
					<button class="btn btn-success" type="button" id="realizar_busqueda_asistencias">BUSCAR</button>
				</span>
			</div>
		 </div>
	
							
		   
		   <div class="panel panel-info">
																	
						 <div class="row">
							 <div class="col-lg-12 col-md-12 col-sm-12">
						
								
											 
								
								
										   <div class="table-responsive">
									
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<tr>
																		<th colspan="5">Asistencias del Sistema (<?php echo $total_filas?>), visualizando desde el <?php echo $registro_ini?> al <?php echo $ULTIMO_REG?></th>
																	</tr>
																	<tr>
																		<th colspan="5">
																		<?php
																		if(isset($acceso_funcionalidades[2]) && trim($acceso_funcionalidades[2])=="1")
																		{																								
																		?>	
																		<a href="/Asistencia/agregarasistencia/"><button class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Agregar</button></a>
																		<?php
																		}
																		?>	
																		</th>
																	</tr>
																	<tr>
																		<th></th>
																		<th>NUM.</th>
																		<th>COLEGIO</th>
																		<th>FECHA ASISTENCIA</th>
																		<th>ESTADO</th>
																	</tr>
																</thead>
																<tbody>
																<?php
																		if(isset($datosasistencias))
																		{
																			foreach($datosasistencias as $clave => $valor)
																			{
																			?>
																				<tr>
																					<td>
																					    
																						
																						 <div class="btn-group">
																							<button data-toggle="dropdown" class="btn btn-warning dropdown-toggle">Opci&oacute;n <span class="caret"></span></button>
																							<ul class="dropdown-menu">
																								<?php
																								if(isset($acceso_funcionalidades[1]) && trim($acceso_funcionalidades[1])=="1")
																								{																								
																								?>
																								<li><a href="#" onclick="graba_lectura_notificaciones('<?php echo $valor["ED05_ASISTENCIAID"]?>');" data-toggle="modal" data-target="#myModal_<?php echo $valor["ED05_ASISTENCIAID"]?>">Detalle</a></li>
																								<?php
																								}

																								if($valor["ED05_ESTADO"]=="PENDIENTE" || $valor["ED05_ESTADO"]=="GESTIONADO")
																								{ 
																										if(isset($acceso_funcionalidades[3]) && trim($acceso_funcionalidades[3])=="1")
																										{																								
																										?>	
																										<li><a href="#" onclick="carga_editar('<?php echo $valor["ED05_ASISTENCIAID"]?>')">Editar</a></li>
																										<?php
																										}
																								
																								}
																								if($valor["ED05_ESTADO"]=="PENDIENTE")
																								{ 
																										if(isset($acceso_funcionalidades[4]) && trim($acceso_funcionalidades[4])=="1")
																										{																								
																										?>	
																										<li><a href="#" onclick="accion_eliminar('<?php echo $valor["ED05_ASISTENCIAID"]?>')">Eliminar</a></li>
																										<?php
																										}
																								}
																								if($valor["ED05_ESTADO"]=="DERIVADO")
																								{ 
																								?>
																										<li class="divider"></li>
																										<?php
																										if(isset($acceso_funcionalidades[5]) && trim($acceso_funcionalidades[5])=="1")
																										{																								
																										?>	
																										<li><a href="/Bitacoraasistencia/agregarbitacoraasistencia/asistenciaid/<?php echo $valor["ED05_ASISTENCIAID"]?>">Seguimiento</a></li>
																										<?php
																										}
																								}			
																								?>
																							</ul>
																						</div>
																						
																					
																					
																						<div class="modal fade" id="myModal_<?php echo $valor["ED05_ASISTENCIAID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																								<div class="modal-dialog">
																											<div class="modal-content">
																								
																														<div class="modal-header">
																															<button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button>
																															<h4 class="modal-title" id="myModalLabel"><strong>ASISTENCIA NUMERO : <?php echo $valor["ED05_ASISTENCIAID"]?></strong><?php echo $valor["TEXTO_ASOCIADOS"]?></h4>
																														</div>
																														<div class="modal-body">
																					
																					
																					
																															 <div class="panel panel-default">
																																<div class="panel-heading">
																																	DETALLE ASISTENCIA
																																</div>
																																<div class="panel-body">
																																	<ul class="nav nav-tabs">
																																		<li class="active"><a href="#home<?php echo $valor["ED05_ASISTENCIAID"]?>" data-toggle="tab">INFO</a>
																																		</li>
																																	
																																		<?php
																																		if(isset($datos_seguimiento))
																																		{
																																			foreach($datos_seguimiento as $clave_seg => $valor_seg)
																																			{
																																				if($valor_seg["ED05_ASISTENCIAID"]==$valor["ED05_ASISTENCIAID"])
																																				{
																																			?>
																																			<li class=""><a href="#profile<?php echo $valor_seg["ED06_SEGASISTENCIAID"]?>" data-toggle="tab">SEG. <?php echo $valor_seg["ED06_SEGFECHA"]?></a></li>
																																			<?php
																																				}
																																			}
																																		}
																																		?>
																																	
																																	</ul>
																										
																																	<div class="tab-content">
																																		
																																		<div class="tab-pane fade active in" id="home<?php echo $valor["ED05_ASISTENCIAID"]?>">
																																				<br>
																																				<p>
																																				<strong>RBD : </strong><?php echo $valor["SIS03_LABORATORIOID"]?><br><br>
																																				<strong>COLEGIO : </strong><?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?><br><br>
																																				<strong>NUM ASISTENCIA : </strong><?php echo $valor["ED05_ASISTENCIAID"]?><br><br>
																																				<strong>FECHA REGISTRO ASISTENCIA : </strong><?php echo $valor["FECHAASISTENCIA"]?><br><br>
																																				<strong>FECHA A REALIZAR ASISTENCIA : </strong><?php echo $valor["FECHAREALIZARCE"]?><br><br>
																																				
																																				<strong>TELEFONO SOLICITANTE : </strong><?php echo $valor["ED05_TELEFONOSOLICITANTE"]?><br><br>
																																				<strong>EMAIL SOLICITANTE : </strong><?php echo $valor["ED05_EMAILSOLICITANTE"]?><br><br>
																																				<strong>PRIORIDAD : </strong><?php echo $valor["ED05_PRIORIDAD"]?><br><br>
																																				<strong>TIPO CONTACTO : </strong><?php echo $valor["ED05_TIPOCONTACTO"]?><br><br>
																																																									
																																				<strong>DETALLE : </strong><br><?php echo nl2br($valor["ED05_DETALLEASISTENCIAREALIZAR"])?><br><br>
																																				<?php
																																				if(trim($valor["ED05_ARCHIVOADJUNTO"])!="")
																																				{	
																																				?>
																																				<strong>ARCHIVO ADJUNTO : </strong><br>
																																				
																																				<strong><a href="<?php echo $valor["ED05_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor["ED05_NOMBREARCHIVOADJUNTO"]?></a></strong>
																																				
																																				<br><br>
																																				
																																				<?php
																																				}
																																				?>
																																				<strong>SOLICITANTE : </strong><?php echo $valor["ED05_NOMBRESOLICITANTE"]?><br><br>
																																				<strong>ULTIMA ACTUALIZACI&Oacute;N : </strong><?php echo $valor["FECHAULTIMAACTUALIZACION"]?><br><br>
																																				<strong>ESTADO : </strong><?php echo $valor["ED05_ESTADO"]?><br><br>
																																	
																																				<?php 
																																				$IDTICKET=$valor["ED05_ASISTENCIAID"];
																																	
																																				if(isset($datos_derivados["$IDTICKET"]["ED01_USUARIOID"]))
																																				{
																																				?>
																																				<button type="button" class="btn btn-lg btn-success">DERIVADO A : </strong><?php echo $datos_derivados["$IDTICKET"]["ED01_USUARIOID"]?></button>
																																				<br><br>	
																																				<?php
																																				}
																																				?>
																																				</p>
																																
																																		</div>
																																	
																																
																																	  <?php
																																		if(isset($datos_seguimiento))
																																		{
																																			foreach($datos_seguimiento as $clave_seg => $valor_seg)
																																			{
																																				if($valor_seg["ED05_ASISTENCIAID"]==$valor["ED05_ASISTENCIAID"])
																																				{
																																			?>
																																			<div class="tab-pane fade" id="profile<?php echo $valor_seg["ED06_SEGASISTENCIAID"]?>">
																																				<br>
																																				<p>
																																				<strong>USUARIO : </strong><?php echo $valor_seg["ED01_USUARIOID"]?><br><br>
																																				<strong>FECHA : </strong><?php echo $valor_seg["ED06_SEGFECHA"]?><br><br>
																																				<strong>DETALLE : </strong><br><?php echo nl2br($valor_seg["ED06_SEGCOMENTARIOS"])?><br><br>
																																																									
																																				<?php
																																				if(trim($valor_seg["ED06_ARCHIVOADJUNTO"])!="")
																																				{	
																																				?>
																																				<strong>ARCHIVO ADJUNTO : </strong><br>
																																				
																																				<strong><a href="<?php echo $valor_seg["ED06_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor_seg["ED06_NOMBREARCHIVOADJUNTO"]?></a></strong>
																																				
																																				<br><br>
																																				
																																				<?php
																																				}
																																				?>
																																				<strong>COMENTARIO DEL SEGUIMIENTO : </strong><br><?php echo nl2br($valor_seg["ED06_REGISTRODETALLECAMBIO"])?><br><br>
																																				</p>
																																			</div>
																																		
																																		
																																			<?php
																																				}
																																			}
																																		}
																																		?>
																																	
																																	
																																	
																																	</div>
																																</div>
																															</div>
																																																											
																												
																														</div>
																														<div class="modal-footer">
																															<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
																														</div>
																										
																								
																											</div>
																								</div>
																						</div>

																					
																					
																					
																					
																					
																					</td>
																				
																					<td><?php echo $valor["ED05_ASISTENCIAID"]?></td>
																					<td><?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?></td>
																					<td><?php echo $valor["FECHAASISTENCIA"]?></td>
																					<td><?php echo $valor["ED05_ESTADO"]?></td>
																				</tr>
																			<?
																			}
																		}		
																?>
																</tbody>
														   </table>
												
															<ul class="pagination">
															  <?php
															  for($i=1;$i<=$num_paginas;$i++)
															  {
															  ?>	
															  <li <?php if(intval($pagina)==intval($i)){?>class="active"<?php }?>><a href="#" onclick="carga_pagina('<?php echo $i;?>','<?php echo $busqueda?>')"><?php echo $i;?> <?php if(intval($pagina)==intval($i)){?><span class="sr-only">(current)</span><?php }?></a></li>
															  <?
															  }
															  ?>	
															</ul>
											   
											   </div>

								
							 </div>
						 </div>
		
				 </div>
	 </div>
