<?php
	
	if(isset($this->layout()->datoscolegio))
		$datoscolegio=$this->layout()->datoscolegio;

	if(isset($this->layout()->datosproducto))
		$datosproducto=$this->layout()->datosproducto;
	

?>



	<!-- date-range-picker -->
	<script src="/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
	<link rel="stylesheet" href="/assets/css/jquery-ui.css">
	<script src="/assets/js/jquery-ui.js"></script>


	<!-- FILEUPLOAD -->
	<script src="/assets/js/bootstrap-fileupload.js"></script>
	<link rel="stylesheet" href="/assets/css/bootstrap-fileupload.min.css"/>


	 <script type="text/javascript">
		
		   $(document).ready(function() {
		
		
				$( "#calendario" ).datepicker();
	 
	
				$("#btn_guardar").click(function(){
	
	
					var val = $("#colegio").val();
					var obj = $("#colegio_lista").find("option[value='" + val + "']");
					
					if(obj != null && obj.length > 0)
					{
						//OK  
					}else{
							alert("Debe Ingresar Correctamente el Colegio Asociado");
							$("#colegio").focus();
							return false;
						 }	
						
					
					if(!$("#producto").val())
					{
						alert("Debe Seleccionar el Producto");
						$("#producto").focus();
						return false;
					}
					
									
					if($("#calendario").val().length<10)
					{
						alert("Debe Ingresar la Fecha de Solicitud");
						$("#calendario").focus();
						return false;
					} 
					
					
					if($("#detalle").val().length<5)
					{
						alert("Debe Ingresar el Detalle de la Solicitud");
						$("#detalle").focus();
						return false;
					} 
				
	
					if (!confirm("Desea Guardar la Solicitud?")) 
					{
					
						return false;
					
					} else {
					
							grabar();
										
					}
					
	
	
	
				});
			}); 
	
	
			function grabar()
			{
	
				var parametros = {
										"colegio" : $("#colegio").val(),
										"producto" : $("#producto").val(),
										"calendario" : $("#calendario").val(),
										"detalle" : $("#detalle").val(),
										"archivo" : $("#archivo").val(),
										"accion" : 'grabar'
								};
				
				
				
				
				$.ajax({
								data:  parametros,
								url:   '/Solicitud/agregarsolicitudprocess', 
								type:  'post', 
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel-body'><h4 class='alert alert-info' style='line-height:50px;'>Procesando solicitud..</h4></div>");
														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
													$("#divNotificaciones").html("<div class='panel-body'><a href='/Solicitud'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a><h4 class='alert alert-info' style='line-height:50px;'>Datos almacenados correctamente</h4></div>");
													$('#volver_bot').focus();
													//limpia formulario
													$('#oForm').trigger("reset");
											
											}else{
												
													$("#divNotificaciones").html("<div class='panel-body'><h4 class='alert alert-info' style='line-height:50px;'>"+res[1]+"</h4></div>");
												
											}
										
								}
						});
		  
			} 	
	
	
	
	
	
	</script>


 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
							    <div class='panel-body'>
									<a href="/Solicitud"><button type="button" class="btn btn-danger">Volver</button></a>
                           		</div>
						   </div>	
				
				
							<div class="panel panel-danger">
				
									<div class="panel-heading">
                                       <strong>INGRESO SOLICITUD</strong>
                                    </div>
                                    <div class="panel-body">
				
				                            <form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
												 
												    <div class="form-group">
                                                        <label>Colegio</label>

                                                        <input list="colegio_lista" class="form-control" id="colegio">
														<datalist id="colegio_lista">
															<?php
															if(isset($datoscolegio))
															{
																foreach($datoscolegio as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?>">
																<?
																}
															}		
															?>
														</datalist>
														
											
												  </div>
                                                  
												   <div class="form-group">
                                                        <label>Producto</label>
                                                        <select class="form-control" id="producto" name="producto">
															<?php
															if(isset($datosproducto))
															{
																foreach($datosproducto as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS04_PRODUCTOID"]?>"><?php echo $valor["SIS04_PRODUCTODESCRIPCION"]?></option>
																<?
																}
															}		
															?>
														</select>
													</div>
                                                  
												  
													   <div class="form-group">
															<label>Fecha Solicitud</label>
															<input type="text" class="form-control" id="calendario">
													   </div>
													  
												 
														<div class="form-group">
															<label>Detalle Solicitud</label>
															<textarea class="form-control" rows="10" id="detalle" name="detalle"></textarea>
														</div>
										   
															 
														 <div class="form-group">
															<label class="control-label col-lg-4">Archivo adjunto </label>
															<div class="">
																 <input type="file" name="archivo" id="archivo" class="btn btn-info">
															</div>
														</div>
														 
															 
													
											
																	
													  <button type="button" class="btn btn-info" id="btn_guardar">Guardar</button>



										    </form>
                                    </div>

							</div>
				
					 </div>
				 </div>

 </div>
 
 <script>
 $( function() {
 } );
 </script>
 
  