<?php
	
	if(isset($this->layout()->datoscolegio))
		$datoscolegio=$this->layout()->datoscolegio;

	if(isset($this->layout()->datosproducto))
		$datosproducto=$this->layout()->datosproducto;
	

?>
	<script type="text/javascript">
		
		   
		   var match= ["application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","image/jpeg","image/png","image/jpg","image/gif","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel","application/pdf"];
			
		
		   $(document).ready(function() {
		
		
				$("#archivo").change(function() {
			
					var file = this.files[0];
					var imagefile = file.type;
					
					if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2]) || (imagefile==match[3]) || (imagefile==match[4]) || (imagefile==match[5]) || (imagefile==match[6]) || (imagefile==match[7]) || (imagefile==match[8]) || (imagefile==match[9]) || (imagefile==match[10]) || (imagefile==match[11]))){
						alert('Por favor seleccione un archivo del tipo (JPEG / JPG / PNG / GIF / TXT / DOC / XLS / PDF / PPT).');
						$("#archivo").val('');
						return false;
					}
			
				});
		
		
		
				$("#calendario").datepicker({dateFormat: 'dd/mm/yy'});
	 
	
				$("#btn_guardar").click(function(){
	
	
					var val = $("#colegio").val();
					var obj = $("#colegio_lista").find("option[value='" + val + "']");
					
					if(obj != null && obj.length > 0)
					{
						//OK  
					}else{
							alert("Debe Ingresar Correctamente el Colegio Asociado");
							$("#colegio").focus();
							return false;
						 }	
						
					
					if(!$("#producto").val())
					{
						alert("Debe Seleccionar el Producto");
						$("#producto").focus();
						return false;
					}
					
									
					if($("#calendario").val().length<10)
					{
						alert("Debe Ingresar la Fecha de Solicitud");
						$("#calendario").focus();
						return false;
					} 
					
					
					if($("#detalle").val().length<5)
					{
						alert("Debe Ingresar el Detalle de la Solicitud");
						$("#detalle").focus();
						return false;
					} 
			
					
	
					if (!confirm("Desea Guardar la Solicitud?")) 
					{
					
						return false;
					
					} else {
					
							grabar();
										
					}
					
	
	
	
				});
			}); 
	
	
			function grabar()
			{
	
				
				var file_data = $('#archivo').prop('files')[0];   
				var form_data = new FormData();                  
				form_data.append('file', file_data);
				form_data.append('colegio',$("#colegio").val());
				form_data.append('producto', $("#producto").val());
				form_data.append('calendario', $("#calendario").val());
				form_data.append('detalle', $("#detalle").val());
				form_data.append('archivo', $("#archivo").val());
				form_data.append('accion', 'grabar');
				
				
				$.ajax({
								url:   '/Solicitud/agregarsolicitudprocess', 
								dataType: 'text',  
								cache: false,
								contentType: false,
								processData: false,
								data: form_data,                         
								type: 'post',
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>Procesando solicitud..</div></div>");

														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
													
													$("#formulario").html("<div class='panel panel-success'><div class='panel-heading' id='volver_frame'>Datos almacenados correctamente<br><br><a href='/Solicitud/index/busqueda/"+res[1]+"'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a></div></div>");
													$('#volver_bot').focus();
													
											
											
											}else{
												
													$("#divNotificaciones").html("<div class='panel panel-primary'><div class='panel-heading'>"+res[1]+"</div></div>");

												
											}
										
								}
						});
		  
			} 	
	
	
	
	
	
	</script>


<div id="formulario">

 	<div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
						   </div>	
				
				
							<div class="panel panel-default">
				
									<div class="panel-heading">
                                        <button type="button" class="btn btn btn-default">INGRESO SOLICITUD</button>
										<a href="/Solicitud"><button type="button" class="btn btn btn-danger" id="volver_bot">VOLVER</button></a>
							        </div>
                    			
								
								    <div class="panel-body">
				
				                            <form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
												 
												    <div class="form-group">
                                                        <label>Colegio (*)</label>

                                                        <input list="colegio_lista" class="form-control" id="colegio">
														<datalist id="colegio_lista">
															<?php
															if(isset($datoscolegio))
															{
																foreach($datoscolegio as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?>">
																<?
																}
															}		
															?>
														</datalist>
														
											
												  </div>
                                                  
												   <div class="form-group">
                                                        <label>Producto (*)</label>
                                                        <select class="form-control" id="producto" name="producto">
															<?php
															if(isset($datosproducto))
															{
																foreach($datosproducto as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS04_PRODUCTOID"]?>"><?php echo $valor["SIS04_PRODUCTODESCRIPCION"]?></option>
																<?
																}
															}		
															?>
														</select>
													</div>
                                                  
												  
													   <div class="form-group">
															<label>Fecha Solicitud (*)</label>
															<input type="text" class="form-control" id="calendario" readonly="readonly" value="<?php echo date("d/m/Y")?>">
													   </div>
													  
												 
														<div class="form-group">
															<label>Detalle Solicitud (*)</label>
															<textarea class="form-control" rows="10" id="detalle" name="detalle"></textarea>
														</div>
										   
															 
														 <div class="form-group" style="background-color:#EEEEEE">
															<label class="control-label col-lg-4">Archivo adjunto </label>
															<div class="">
																 <input type="file" name="archivo" id="archivo" class="btn btn-info">
															</div>
														</div>
														 
															 
													
											
																	
													  <button type="button" class="btn btn-info" id="btn_guardar">Guardar</button>



										    </form>
                                    </div>

							</div>
				
					 </div>
				 </div>

 		</div>
	
 </div>