<?php
	
	if(isset($this->layout()->datoscolegio))
		$datoscolegio=$this->layout()->datoscolegio;

	if(isset($this->layout()->datosproducto))
		$datosproducto=$this->layout()->datosproducto;
	
	
	
	$SOLICITUDID=$this->layout()->SOLICITUDID;
	$LABORATORIOID=$this->layout()->LABORATORIOID;
	$PRODUCTOID=$this->layout()->PRODUCTOID;
	$FECHASOLICITUD=$this->layout()->FECHASOLICITUD;
	$DETALLESOLICITUD=$this->layout()->DETALLESOLICITUD;
	$ARCHIVOADJUNTO=$this->layout()->ARCHIVOADJUNTO;
	$NOMBREARCHIVOADJUNTO=$this->layout()->NOMBREARCHIVOADJUNTO;
	$TIPOARCHIVOADJUNTO=$this->layout()->TIPOARCHIVOADJUNTO;
	$NOMBRESOLICITANTE=$this->layout()->NOMBRESOLICITANTE;
	$ESTADO=$this->layout()->ED02_ESTADO;
	
	
?>
	<script type="text/javascript">
		
		   
			   var match= ["application/vnd.openxmlformats-officedocument.presentationml.presentation","application/vnd.ms-powerpoint","image/jpeg","image/png","image/jpg","image/gif","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.ms-excel","application/pdf"];
			
			/*		
				$(document).ready(function() {
				
				
						$("#archivo").change(function() {
					
							var file = this.files[0];
							var imagefile = file.type;
							
							if(!((imagefile==match[0]) || (imagefile==match[1]) || (imagefile==match[2]) || (imagefile==match[3]) || (imagefile==match[4]) || (imagefile==match[5]) || (imagefile==match[6]) || (imagefile==match[7]) || (imagefile==match[8]) || (imagefile==match[9]) || (imagefile==match[10]) || (imagefile==match[11]))){
								alert('Por favor seleccione un archivo del tipo (JPEG / JPG / PNG / GIF / TXT / DOC / XLS / PDF / PPT).');
								$("#archivo").val('');
								return false;
							}
					
						});
				
				
				
						$("#calendario").datepicker({dateFormat: 'dd/mm/yy'});
			 
			
				}); 
				*/
				
				
	
	
				function valida_grabar()
				{
		
					
			
							var val = $("#colegio").val();
							var obj = $("#colegio_lista").find("option[value='" + val + "']");
							
							if(obj != null && obj.length > 0)
							{
								//OK  
							}else{
									alert("Debe Ingresar Correctamente el Colegio Asociado");
									$("#colegio").focus();
									return false;
								 }	
								
							
							if(!$("#producto").val())
							{
								alert("Debe Seleccionar el Producto");
								$("#producto").focus();
								return false;
							}
							
											
							if($("#calendario").val().length<10)
							{
								alert("Debe Ingresar la Fecha de Solicitud");
								$("#calendario").focus();
								return false;
							} 
							
							
							if($("#detalle").val().length<5)
							{
								alert("Debe Ingresar el Detalle de la Solicitud");
								$("#detalle").focus();
								return false;
							} 
					
							
			
							if (!confirm("Desea Guardar la Solicitud?")) 
							{
							
								return false;
							
							} else {
							
									grabar();
												
							}
							
			
					}
			
			}
	
	
	
			function grabar()
			{
	
				
				var file_data = $('#archivo').prop('files')[0];   
				var form_data = new FormData();                  
				form_data.append('file', file_data);
				
				form_data.append('solicitudid',$("#solicitudid").val());
				form_data.append('colegio',$("#colegio").val());
				form_data.append('producto', $("#producto").val());
				form_data.append('calendario', $("#calendario").val());
				form_data.append('detalle', $("#detalle").val());
				form_data.append('archivo', $("#archivo").val());
				form_data.append('estado', $("#estado").val());
				form_data.append('accion', 'grabar');
				
				
				$.ajax({
								url:   '/Solicitud/editarsolicitudprocess', 
								dataType: 'text',  
								cache: false,
								contentType: false,
								processData: false,
								data: form_data,                         
								type: 'post',
								beforeSend: function () {
															$("#divNotificaciones").html("<div class='panel-body'><h4 class='alert alert-info' style='line-height:50px;'>Procesando solicitud..</h4></div>");
														},
		
								success:  function (response) { 
								
											var str=response;
											var res = str.split("|");
									
											if(res[0]=='OK')
											{
												$("#formulario").html("<div class='panel-body' id='volver_frame'><a href='/Solicitud'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a><h4 class='alert alert-info' style='line-height:50px;'>Datos almacenados correctamente</h4></div>");
												$('#volver_bot').focus();
									
											}else{
												
													$("#formulario").html("<div class='panel-body' id='volver_frame'><a href='/Solicitud'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a><h4 class='alert alert-info' style='line-height:50px;'>"+res[1]+"</h4></div>");
													$('#volver_bot').focus();
										
											}
										
								}
						});
		  
			} 	
	
	
	
	
	
	</script>


 <div class="col-md-12">
  			 <div class="row">
					 <div class="col-md-6 col-sm-6 col-xs-12">
											
						   <div id="divNotificaciones">
							    <div class='panel-body'>
									<a href="/Solicitud"><button type="button" class="btn btn-danger">Volver</button></a>
                           		</div>
						   </div>	
				
				
							<div class="panel panel-danger">
				
									<div class="panel-heading">
                                       <strong>INGRESO SOLICITUD</strong>
                                    </div>
                                    <div class="panel-body">
				
				                            <form role="form" id="oForm" name="oForm" enctype="multipart/form-data">
												 
												    <input type="hidden" id="solicitudid" name="solicitudid" value="<?php echo $SOLICITUDID?>">
												 
												    <div class="form-group">
                                                        <label>Colegio</label>

                                                        <input list="colegio_lista" class="form-control" id="colegio">
														<datalist id="colegio_lista">
															<?php
															if(isset($datoscolegio))
															{
																foreach($datoscolegio as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?>" <?php if($LABORATORIOID==$valor["SIS03_LABORATORIOID"]) echo "selected='selected'"?>>
																<?
																}
															}		
															?>
														</datalist>
														
											
												  </div>
                                                  
												   <div class="form-group">
                                                        <label>Producto</label>
                                                        <select class="form-control" id="producto" name="producto">
															<?php
															if(isset($datosproducto))
															{
																foreach($datosproducto as $clave => $valor)
																{
																?>
																	<option value="<?php echo $valor["SIS04_PRODUCTOID"]?>" <?php if($PRODUCTOID==$valor["SIS04_PRODUCTOID"]) echo "selected"?>><?php echo $valor["SIS04_PRODUCTODESCRIPCION"]?></option>
																<?
																}
															}		
															?>
														</select>
													</div>
                                                  
												  
													   <div class="form-group">
															<label>Fecha Solicitud</label>
															<input type="text" class="form-control" id="calendario" readonly="readonly" value="<?php echo $FECHASOLICITUD?>">
													   </div>
													  
												 
														<div class="form-group">
															<label>Detalle Solicitud</label>
															<textarea class="form-control" rows="10" id="detalle" name="detalle"><?php echo $DETALLESOLICITUD?></textarea>
														</div>
										   
															 
														 <div class="form-group">
															<label class="control-label col-lg-4">Archivo adjunto </label>
															<div class="">
																 <input type="file" name="archivo" id="archivo" class="btn btn-info">
																 <?php
																 if(trim($NOMBREARCHIVOADJUNTO)!="")
																 {
																 ?>
																 <br><strong>Archivo actual :</strong> <?php echo $NOMBREARCHIVOADJUNTO?>
																 <?php
																 }
																 ?>
															</div>
														</div>
														 
															 
														 <div class="form-group">
															<label>Estado</label>
															<select class="form-control" id="estado" name="estado">
																<option value="PEN" <?php if($ESTADO=="PEN") echo "selected"?>>PENDIENTE</option>
																<option value="DER" <?php if($ESTADO=="DER") echo "selected"?>>DERIVADO</option>
																<option value="RES" <?php if($ESTADO=="RES") echo "selected"?>>RESUELTO</option>
															</select>
														</div>
																		
													  <button type="button" class="btn btn-info" id="btn_guardar" onclick="valida_grabar()">Guardar</button>



										    </form>
                                    </div>

							</div>
				
					 </div>
				 </div>

 </div>