<?php
if(isset($this->layout()->busqueda))
		$busqueda=$this->layout()->busqueda;
else	
		$busqueda=$this->layout()->busqueda_defecto;
?>
<script type="text/javascript">
 
 
 
	 	function graba_lectura_notificaciones(valores)
		{
		
				var parametros = {
								 tipo:'3',
								 concepto:'solicitud',
								 valores:valores
								 };
		
				$.ajax({
							data:  parametros,
							url:   '/Login/notificacion', 
							type:  'post', 
							evalscripts : true,
							success:  function (response) { 
						
						
							}
						});
		
		}					

 
 
 
 	   function accion_generar(solicitudid,tipo)
	   {
			if(tipo==1)
				window.location="/Incidente/agregarincidente/solicitudid/"+solicitudid;
			
			if(tipo==2)
				window.location="/Asistencia/agregarasistencia/solicitudid/"+solicitudid;
		
 	   }
	   
	   
	   function accion_eliminar(solicitudid)
	   {

				if (!confirm("Desea Eliminar los Datos de la Solicitud?")) 
				{
				
					return false;
				
				} else {
				
							var parametros = {
												"solicitudid" : solicitudid
											};
							
							$.ajax({
											data:  parametros,
											url:   '/Solicitud/eliminarsolicitud', 
											type:  'post', 
											evalscripts : true,
											success:  function (response) { 
											
													$("#formulario").html("<div class='panel panel-success'><div class='panel-heading' id='volver_frame'>"+response+"<br><br><a href='/Solicitud'><button type='button' id='volver_bot' class='btn btn-danger'>Volver</button></a></div></div>");
													$('#volver_bot').focus();
									
																
											}
									});
									
				}

 	   }	
 
 	   function carga_editar(solicitudid)
	   {

					var parametros = {
										"solicitudid" : solicitudid
									};
					
					$.ajax({
									data:  parametros,
									url:   '/Solicitud/editarsolicitud', 
									type:  'post', 
									evalscripts : true,
									success:  function (response) { 
									
											$("#formulario").html(response);
														
									}
							});

		}	   



 	   function carga_pagina(pagina,busqueda)
	   {

					var parametros = {
										"pagina" : pagina,
										"busqueda" : busqueda 
									};
					
					$.ajax({
									data:  parametros,
									url:   '/Solicitud/listarsolicitudes', 
									type:  'post', 
									evalscripts : true,
									success:  function (response) { 
									
											$("#formulario").html(response);
														
									}
							});

		}	


		//carga inicial
		carga_pagina('1','<?php echo $busqueda?>');
</script>
<div id="formulario">
		
</div>						
