<?php
	
	if(isset($this->layout()->datossolicitudes))
		$datossolicitudes=$this->layout()->datossolicitudes;
	
	if(isset($this->layout()->total_filas))
		$total_filas=$this->layout()->total_filas;
	
	if(isset($this->layout()->pagina))
		$pagina=$this->layout()->pagina;

	if(isset($this->layout()->num_paginas))
		$num_paginas=$this->layout()->num_paginas;

	if(isset($this->layout()->registro_ini))
		$registro_ini=$this->layout()->registro_ini;

	if(isset($this->layout()->registro_fin))
		$registro_fin=$this->layout()->registro_fin;
	
	if(isset($this->layout()->busqueda))
		$busqueda=$this->layout()->busqueda;
		
	
	if($total_filas < $registro_fin)
	   $ULTIMO_REG=$total_filas;
	else   
	   $ULTIMO_REG=$registro_fin;
	
	
?>
<script type="text/javascript">
 
	   
	   $("#realizar_busqueda").click( function()
       {
         	if($("#busqueda").val()!="")
			{
				carga_pagina('1',$("#busqueda").val());
		  	}
		 }
        );
	   
   
	   
</script>
	   
<div class="col-md-12">
		   
		   <div id="divNotificacionesCentral">
		   </div>									 
						
						
						
		<div class="panel-footer">
			<div class="input-group">
				<input type="text" name="busqueda" id="busqueda" class="form-control" value="<?php echo $busqueda?>" placeholder="" data-toggle="tooltip" title="Puedes buscar por : RBD / NUM SOLICITUD / ESTADO (PEN - DER - RES)" />
				<span class="input-group-btn">
					<button class="btn btn-success" type="button" id="realizar_busqueda">SEND</button>
				</span>
			</div>
		 </div>
	
							
		   
		   <div class="panel panel-info">
																	
						 <div class="row">
							 <div class="col-lg-12 col-md-12 col-sm-12">
						
								
											 
								
								
										   <div class="table-responsive">
									
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<tr>
																		<th colspan="5">Solicitudes del Sistema (<?php echo $total_filas?>), visualizando desde el <?php echo $registro_ini?> al <?php echo $ULTIMO_REG?></th>
																	</tr>
																	<tr>
																		<th colspan="5">
																		<a href="/Solicitud/agregarsolicitud/"><button class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Agregar</button></a>
																		</th>
																	</tr>
																	<tr>
																		<th>NUM.SOL.</th>
																		<th>COLEGIO</th>
																		<th>FECHA SOLICITUD</th>
																		<th>ESTADO</th>
																		<th>OPCIONES</th>
																	</tr>
																</thead>
																<tbody>
																<?php
																		if(isset($datossolicitudes))
																		{
																			foreach($datossolicitudes as $clave => $valor)
																			{
																			?>
																				<tr>
																					<td><?php echo $valor["ED02_SOLICITUDID"]?></td>
																					<td><?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?></td>
																					<td><?php echo $valor["FECHASOLICITUD"]?></td>
																					<td><?php echo $valor["ED02_ESTADO"]?></td>
																					<td>
																					  <button onclick="carga_editar('<?php echo $valor["ED02_SOLICITUDID"]?>')" id="btn_editar" class="btn btn-primary"><i class="glyphicon glyphicon-search"></i>Editar</button>
																					  <button onclick="accion_eliminar('<?php echo $valor["ED02_SOLICITUDID"]?>')" class="btn btn-danger"><i class="glyphicon glyphicon-home"></i>Eliminar</button>
																					  <button class="btn btn-success" data-toggle="modal" data-target="#myModal_<?php echo $valor["ED02_SOLICITUDID"]?>">Detalle</button>
																					
																					
																					
																						<div class="modal fade" id="myModal_<?php echo $valor["ED02_SOLICITUDID"]?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
																								<div class="modal-dialog">
																											<div class="modal-content">
																								
																														<div class="modal-header">
																															<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
																															<h4 class="modal-title" id="myModalLabel">Solicitud n&uacute;mero : <?php echo $valor["ED02_SOLICITUDID"]?></h4>
																														</div>
																														<div class="modal-body">
																															
																															<strong>RBD : </strong><?php echo $valor["SIS03_LABORATORIOID"]?><br><br>
																															<strong>COLEGIO : </strong><?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?><br><br>
																															<strong>PRODUCTO : </strong><?php echo $valor["SIS04_PRODUCTOID"]?><br><br>
																															<strong>FECHA SOLICITUD : </strong><?php echo $valor["FECHASOLICITUD"]?><br><br>
																															<strong>DETALLE : </strong><br><?php echo nl2br($valor["ED02_DETALLESOLICITUD"])?><br><br>
																															<?php
																															if(trim($valor["ED02_ARCHIVOADJUNTO"])!="")
																															{	
																															?>
																															<strong>ARCHIVO ADJUNTO : </strong><br>
																															
																															<strong><a href="<?php echo $valor["ED02_ARCHIVOADJUNTO"]?>" target="_blank"><?php echo $valor["ED02_NOMBREARCHIVOADJUNTO"]?></a></strong>
																															
																															<br><br>
																															
																															<?php
																															}
																															?>
																															<strong>SOLICITANTE : </strong><?php echo $valor["ED02_NOMBRESOLICITANTE"]?><br><br>
																															<strong>FECHA INGRESO : </strong><?php echo $valor["FECHAINGRESO"]?><br><br>
																															<strong>ULTIMA ACTUALIZACI&Oacute;N : </strong><?php echo $valor["FECHAULTIMAACTUALIZACION"]?><br><br>
																															<strong>ESTADO : </strong><?php echo $valor["ED02_ESTADO"]?><br><br>
																												
																												
																														</div>
																														<div class="modal-footer">
																															<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
																														</div>
																										
																								
																											</div>
																								</div>
																						</div>

																					
																					
																					
																					
																					
																					</td>
																				</tr>
																			<?
																			}
																		}		
																?>
																</tbody>
														   </table>
												
															<ul class="pagination">
															  <?php
															  for($i=1;$i<=$num_paginas;$i++)
															  {
															  ?>	
															  <li <?php if(intval($pagina)==intval($i)){?>class="active"<?php }?>><a href="#" onclick="carga_pagina('<?php echo $i;?>','<?php echo $busqueda?>')"><?php echo $i;?> <?php if(intval($pagina)==intval($i)){?><span class="sr-only">(current)</span><?php }?></a></li>
															  <?
															  }
															  ?>	
															</ul>
											   
											   </div>

								
							 </div>
						 </div>
		
				 </div>
	 </div>
