<?php
	
	if(isset($this->layout()->datossolicitudes))
		$datossolicitudes=$this->layout()->datossolicitudes;
	
	if(isset($this->layout()->total_filas))
		$total_filas=$this->layout()->total_filas;
	
	if(isset($this->layout()->pagina))
		$pagina=$this->layout()->pagina;

	if(isset($this->layout()->num_paginas))
		$num_paginas=$this->layout()->num_paginas;

	if(isset($this->layout()->registro_ini))
		$registro_ini=$this->layout()->registro_ini;

	if(isset($this->layout()->registro_fin))
		$registro_fin=$this->layout()->registro_fin;
		
	
	if($total_filas < $registro_fin)
	   $ULTIMO_REG=$total_filas;
	else   
	   $ULTIMO_REG=$registro_fin;
	
	
?>
<div class="col-md-12">
		   
		   <div id="divNotificacionesCentral">
		   </div>									 
							
		   
		   <div class="panel panel-info">
																	
						 <div class="row">
							 <div class="col-lg-12 col-md-12 col-sm-12">
						
								
										   <div class="table-responsive">
									
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<tr>
																		<th colspan="5">Solicitudes del Sistema (<?php echo $total_filas?>), visualizando desde el <?php echo $registro_ini?> al <?php echo $ULTIMO_REG?></th>
																	</tr>
																	<tr>
																		<th colspan="5">
																		<a href="/Solicitud/agregarsolicitud/"><button class="btn btn-inverse"><i class="glyphicon glyphicon-plus"></i>Agregar</button></a>
																		</th>
																	</tr>
																	<tr>
																		<th>NUM SOLICITUD</th>
																		<th>COLEGIO</th>
																		<th>FECHA SOLICITUD</th>
																		<th>ESTADO</th>
																		<th>OPCIONES</th>
																	</tr>
																</thead>
																<tbody>
																<?php
																		if(isset($datossolicitudes))
																		{
																			foreach($datossolicitudes as $clave => $valor)
																			{
																			?>
																				<tr>
																					<td><?php echo $valor["ED02_SOLICITUDID"]?></td>
																					<td><?php echo $valor["SIS03_LABORATORIOID"]?> | <?php echo $valor["SIS03_LABORATORIODESCRIPCION"]?></td>
																					<td><?php echo $valor["FECHASOLICITUD"]?></td>
																					<td><?php echo $valor["ED02_ESTADO"]?></td>
																					<td>
																					  <button onclick="carga_editar('<?php echo $valor["ED02_SOLICITUDID"]?>')" id="btn_editar" class="btn btn-primary"><i class="glyphicon glyphicon-search"></i>Editar</button>
																					  <button onclick="accion_eliminar('<?php echo $valor["ED02_SOLICITUDID"]?>')" class="btn btn-danger"><i class="glyphicon glyphicon-home"></i>Eliminar</button>
																					</td>
																				</tr>
																			<?
																			}
																		}		
																?>
																</tbody>
														   </table>
												
															<ul class="pagination">
															  <?php
															  for($i=1;$i<=$num_paginas;$i++)
															  {
															  ?>	
															  <li <?php if(intval($pagina)==intval($i)){?>class="active"<?php }?>><a href="#" onclick="carga_pagina('<?php echo $i;?>')"><?php echo $i;?> <?php if(intval($pagina)==intval($i)){?><span class="sr-only">(current)</span><?php }?></a></li>
															  <?
															  }
															  ?>	
															</ul>
											   
											   </div>

								
							 </div>
						 </div>
		
				 </div>
	 </div>