<?php
$action=$this->layout()->action;
?>
<script type="text/javascript">
 
 
 	   function carga_listado(pagina,fechainicio,fechatermino,usuario)
	   {

					var parametros = {
										"pagina" : pagina,
										"fechainicio" : fechainicio,
										"fechatermino" : fechatermino,
										"usuario" : usuario
										
									};
					
					$.ajax({
									data:  parametros,
									url:   '<?php echo $action?>', 
									type:  'post', 
									evalscripts : true,
									success:  function (response) { 
									
											$("#formulario").html(response);
														
									}
							});

		}	


		//carga inicial
		carga_listado('1','<?php echo date("d/m/Y",strtotime(date("d-m-Y")."- 7 days"))?>','<?php echo date("d/m/Y")?>','-');

</script>
<div id="formulario">
		
</div>