<?php

	$texto_columna_1=$this->layout()->texto_columna_1;
	$texto_columna_2=$this->layout()->texto_columna_2;
	$texto_columna_3=$this->layout()->texto_columna_3;
	$texto_columna_4=$this->layout()->texto_columna_4;
	$titulo_reporte=$this->layout()->titulo_reporte;
	
	if(isset($this->layout()->datosinforme))
		$datosinforme=$this->layout()->datosinforme;

	if(isset($this->layout()->datosusuarios))
		$datosusuarios=$this->layout()->datosusuarios;
	
	if(isset($this->layout()->total_filas))
		$total_filas=$this->layout()->total_filas;
	
	if(isset($this->layout()->pagina))
		$pagina=$this->layout()->pagina;

	if(isset($this->layout()->num_paginas))
		$num_paginas=$this->layout()->num_paginas;

	if(isset($this->layout()->registro_ini))
		$registro_ini=$this->layout()->registro_ini;

	if(isset($this->layout()->registro_fin))
		$registro_fin=$this->layout()->registro_fin;
	
	if(isset($this->layout()->busqueda))
		$busqueda=$this->layout()->busqueda;
	
	if(isset($this->layout()->fechainicio))
		$fechainicio=$this->layout()->fechainicio;
		
	if(isset($this->layout()->fechatermino))
		$fechatermino=$this->layout()->fechatermino;

	if(isset($this->layout()->usuario))
		$usuario=$this->layout()->usuario;
		
	
	if($total_filas < $registro_fin)
	   $ULTIMO_REG=$total_filas;
	else   
	   $ULTIMO_REG=$registro_fin;
	
	
?>
<script type="text/javascript">
 
	   
			   $("#realizar_busqueda").click( function()
			   {
				
				
						if($("#calendario1").val().length<10)
						{
								alert("Debe Ingresar Fecha Inicio");
								$("#calendario1").focus();
								return false;
						}
					
						if($("#calendario2").val().length<10)
						{
								alert("Debe Ingresar Fecha Termino");
								$("#calendario2").focus();
								return false;
						}
					
	
						carga_listado('1',$("#calendario1").val(),$("#calendario2").val(),$("#usuario").val());
				 }
				);
	
	
				$("#calendario1").datepicker({dateFormat: 'dd/mm/yy'});
	   			$("#calendario2").datepicker({dateFormat: 'dd/mm/yy'});
	   
	      
	
	   
</script>
	   
<div class="col-md-12">
		   
		<div id="divNotificacionesCentral">
	    </div>									 
						
						
		<div class="panel-footer">
	
			<div class="row">
				<div class="col-md-4 col-sm-4">
						<label>Fecha Desde (*)</label>
						<input type="text" class="form-control" id="calendario1" readonly="readonly" value="<?php echo $fechainicio?>">
				</div>												 
				<div class="col-md-4 col-sm-4">
						<label>Fecha Hasta (*)</label>
						<input type="text" class="form-control" id="calendario2" readonly="readonly" value="<?php echo $fechatermino?>">
				</div>  
		
				<div class="col-md-4 col-sm-4">
				
					<label>Usuario</label>
					<select class="form-control" id="usuario" name="usuario">
						<option value="-" <?php if($usuario=="-") echo "selected"?>>TODOS</option>
						<?php
						if(isset($datosusuarios))
						{
							foreach($datosusuarios as $clave => $valor)
							{
							?>
								<option value="<?php echo $valor["USUARIOID"]?>" <?php if($usuario==$valor["USUARIOID"]) echo "selected"?>><?php echo $valor["NOMBREAPELLIDO"]?></option>
							<?
							}
						}		
						?>
					</select>

				</div>  
		
		
			</div>		  
			<div class="row">
				<div class="col-md-4 col-sm-4">
						<button class="btn btn-success" type="button" id="realizar_busqueda">BUSCAR</button>
				</div>  
			</div>		  
		 </div>
		 
		   <div class="panel panel-info">
																	
						 <div class="row">
							 <div class="col-lg-12 col-md-12 col-sm-12">
						
										   <div class="table-responsive">
									
															<table class="table table-striped table-bordered table-hover">
																<thead>
																	<tr>
																		<th colspan="4">- <?php echo $titulo_reporte?> (<?php echo $total_filas?>)<br> - Visualizando desde el <?php echo $registro_ini?> al <?php echo $ULTIMO_REG?><br> - Rango fecha <?php echo $fechainicio?> al <?php echo $fechatermino?><?php if($usuario!="-"){?><br> - Usuario <?php echo $usuario?><?php }?></th>
																	</tr>
																	<tr>
																		<th><?php echo $texto_columna_1?></th>
																		<th><?php echo $texto_columna_2?></th>
																		<th><?php echo $texto_columna_3?></th>
																		<th><?php echo $texto_columna_4?></th>
																	</tr>
																</thead>
																<tbody>
																<?php
																		if(isset($datosinforme))
																		{
																			foreach($datosinforme as $clave => $valor)
																			{
																			?>
																				<tr>
																					<td><?php echo $valor["USUARIOID"]?></td>
																					<td><?php echo $valor["FECHA"]?></td>
																					<td><?php echo $valor["ACCION"]?></td>
																					<td><?php echo $valor["MASINFO"]?></td>
																				</tr>
																			<?
																			}
																		}		
																?>
																</tbody>
														   </table>
												
															<ul class="pagination">
															  <?php
															  for($i=1;$i<=$num_paginas;$i++)
															  {
															  ?>	
															  <li <?php if(intval($pagina)==intval($i)){?>class="active"<?php }?>><a href="#" onclick="carga_listado('<?php echo $i;?>','<?php echo $fechainicio?>','<?php echo $fechatermino?>','<?php echo $usuario?>')"><?php echo $i;?> <?php if(intval($pagina)==intval($i)){?><span class="sr-only">(current)</span><?php }?></a></li>
															  <?
															  }
															  ?>	
															</ul>
											   
											   </div>

								
							 </div>
						 </div>
		
				 </div>
	 </div>